### ISSUE TITLE
We should bump our default pickle version from 2 to 4

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1243]
We currently use in `sherpa.ui.utils.save`

```python
            pickle.dump(self, fout, 2)  # Use newer binary protocol
```

but the default version is now 4 (added in Python 3.4).

I think we should make `version` be an optional argument to `save`, have it default to 4, and then use that in the `dump` call. We don't need the equivalent in `load` since it is determined from the file contents.

Alternatively we could just drop the version field to `dump` and make it just use the default value (which could have long-term issues for users switching between Python/Sherpa versions over time).

**Comment by hamogu** [comment]
:+1: to using the default version. Usually, users *upgrade* sherpa and don't *downgrade*. It's perfectly normal that you can't read all files written by a new version using the old version. So, this only is an issue if you hand the file to a collaborator who uses an older version - good motivation for them to upgrade!
Also, the protocol is changed so infrequently, that it's really not an issue in practice; but using the default means we never ever have to worry and think about this again. I'm :-1: on adding another option for the version because then we have to test that, maintain it etc.
