### ISSUE TITLE
Build scripts do not expand environment variables

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1324]
When I wrote the instructions on https://sherpa.readthedocs.io/en/4.14.0/developer/index.html#install-from-source-in-conda sherpa used to build with settings like this
`fftw-include_dirs=${ASCDS_LIB}/../include` in sherpa's `setup.cfg`
but when I tried the same thing right now, I get 
```
sherpa/utils/src/tcd/tcdTransform.c:46:19: fatal error: fftw3.h: No such file or directory
     #include "fftw3.h"
                       ^
    compilation terminated.
    error: Command "gcc -pthread -B /nfs/melkor/d1/guenther/soft/mambaforge/envs/sherpaciao/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isherpa/include -Isherpa/utils/src -Isherpa/utils/src/tcd -I${ASCDS_LIB}/../include -I/tmp/pip-build-env-kfwhz2po/overlay/lib/python3.8/site-packages/numpy/core/include -I/nfs/melkor/d1/guenther/soft/mambaforge/envs/sherpaciao/include/python3.8 -I/nfs/melkor/d1/guenther/soft/mambaforge/envs/sherpaciao/include/python3.8 -c sherpa/utils/src/tcd/tcdTransform.c -o build/temp.linux-x86_64-3.8/sherpa/utils/src/tcd/tcdTransform.o -MMD -MF build/temp.linux-x86_64-3.8/sherpa/utils/src/tcd/tcdTransform.o.d" failed with exit status 1
```
although the variable is set correctly:
```
(sherpaciao) melkor:/melkor/d1/guenther/soft/python/sherpa> ls ${ASCDS_LIB}/../include/fft*
/nfs/melkor/d1/guenther/soft/mambaforge/envs/sherpaciao/lib/../include/fftw3.f
/nfs/melkor/d1/guenther/soft/mambaforge/envs/sherpaciao/lib/../include/fftw3.f03
/nfs/melkor/d1/guenther/soft/mambaforge/envs/sherpaciao/lib/../include/fftw3.h
/nfs/melkor/d1/guenther/soft/mambaforge/envs/sherpaciao/lib/../include/fftw3l.f03
/nfs/melkor/d1/guenther/soft/mambaforge/envs/sherpaciao/lib/../include/fftw3q.f03
```
It works well if I spell out the locations of the files in sherpa's `setup.cfg`
```
fftw-include_dirs=/nfs/melkor/d1/guenther/soft/mambaforge/envs/sherpaciao/lib/../include
```

However, a number of things have changed that are outside of shepa (I'm using mamaba instead of conda, I'm on a different computer, ...) so I don't know what caused this change.

**At this point, I'm not asking for help to debug this, I'm just opening an issue so that I don't forget to check back; this is the type of problem that might not be reproducable and it also outside of the scope of sherpa itself. What we can do is to update https://sherpa.readthedocs.io/en/4.14.0/developer/index.html#install-from-source-in-conda to account for this.**

**Comment by DougBurke** [comment]
It's not a mamba thing. The use of environment variables hasn't worked for a while and - given how we use them - I'm not sure it ever worked for me (although it seemed to have for you). 

I don't know how setup.cfg gets automatically sucked in to set up the setuptools Extension objects - actually, reading https://stackoverflow.com/questions/27077355/how-to-use-setup-cfg-instead-of-setup-py-with-python-2-7 helps me out, but it is not at all what processing is done to take the value from the `xspec_config` section (say) and set the `xspec-lib-dirs` option used by `helpers/xspec_config.py`.

Rather than trying to work out what is/has happened we just tell users they need to expand their environment variables (unless someone knows the answer), as you suggest above.
