### ISSUE TITLE
Add install option for pure-Python Sherpa core?

### ISSUE THREAD

**Issue by cdeil** [sherpa/sherpa#133]
Is it possible to add an option to the Sherpa build system to install a minimal pure-Python core part of Sherpa?

For [gammapy](https://gammapy.readthedocs.org/en/latest/), [threeml](https://threeml.stanford.edu/) and [naima](http://naima.readthedocs.org/en/latest/) we are debating (have been for a year) whether we can go all-in on Sherpa modeling or whether it has to remain an optional dependency, because it's hard to install of the Fortran / C extensions.
So e.g. currently in Naima there's [models](https://github.com/zblz/naima/blob/master/naima/models.py) and [sherpa wrapper models](https://github.com/zblz/naima/blob/master/naima/sherpa_models.py).

I know the eval function of most of the Sherpa built-in models is written in C extensions, but the `Parameter` and `ArithmeticModel` classes, i.e. the core model classes, are pure-python.

Would it be possible / hard / easy to add an option to the Sherpa build system and make something like `pip install sherpa[core]` work and have the core model classes available, but not have any C / Fortran?

**Comment by olaurino** [comment]
@cdeil, thanks for the suggestion, we'll discuss this.

I have some questions:
  * Did you have issues installing the fortran/c extensions? One of the goals we had when redesigning the install process was to make it easy to install sherpa with a default, streamlined, python-friendly process. If there are still issues to be ironed out it would be good to know. Maybe we need to better document the source build process and options?
  * Would conda binaries be an option for you? Could you take advantage from more frequent binary builds from the master branch?

Thanks!

**Comment by cdeil** [comment]
> we'll discuss this.

Thanks!
As I said, it was just a thought.
If it's a lot of work to implement, it might not be worth the effort because at least for Gammapy, it'll probably remain so that to do likelihood fitting, i.e. most users, we'll rely on Sherpa optimizers and error estimators, i.e. the C extensions.

> Did you have issues installing the fortran/c extensions?

Yes ... I currently have `/opt/local/bin/gfortran-mp-5` as Fortran compiler and I don't know how to tell the Sherpa build to pick it up. I admit I haven't tried to find out ... maybe it is documented how to pass this info to the Sherpa build?

> Would conda binaries be an option for you? Could you take advantage from more frequent binary builds from the master branch?

Yes, conda is a great option.
More frequent binary builds would be helpful, I think.
E.g. we could start using your `wstat` and remove our implementation of wstat in Gammapy now.

The main issue we've had with conda is numpy version conflicts.
Currently our CI is broken Sherpa was built against an older Numpy than Astropy:
https://github.com/gammapy/gammapy/pull/392#issuecomment-163707574
At the `PyGamma15` workshop we have 15 users try to run Sherpa via Gammapy for the first time, and had to find out and give conda install instructions where the order mattered, so that the right numpy is available at the right point of the install:
https://github.com/gammapy/PyGamma15/tree/gh-pages/tutorials/gammapy#how-to-prepare

I don't know what the current status is, but isn't it possible to build a Sherpa conda binary that works with Numpy 1.8 to 1.11? If this isn't the case already with your conda dev builds, and it might be possible, maybe split that out into a separate issue?

**Comment by olaurino** [comment]
> Yes ... I currently have /opt/local/bin/gfortran-mp-5 as Fortran compiler and I don't know how to tell the Sherpa build to pick it up. I admit I haven't tried to find out ... maybe it is documented how to pass this info to the Sherpa build?

Isn't it just a matter of using macports to select a specific version of the compiler? i.e. `sudo port select gcc mp-gcc5` or something like that? Alternatively, you can try and pass the compiler's path through the `F77` variable in the same line you use to call setup.py, e.g. `F77=/opt/local/bin/gfortran-mp-5 python setup.py develop`.

I don't think the latter is documented in our instructions, though, and while I have used that option in the past, I haven't tested it now, so I may be missing something.

> The main issue we've had with conda is numpy version conflicts.
I have personally tested Sherpa 4.8.0 (about to be released) with numpy 1.8, 1.9, and 1.10. We have only one issue with a test that used a comparison broken by the version string 1.10, but no actual functional issues.

Looking at the comment you posted, I wish conda had a better mechanism for dealing with versions. Maybe we should list the numpy dependency in a different way in the conda metadata file and just say  larger than 1.8. It's somewhat unsafe, but it may work with newer untested versions of numpy. Otherwise we should have different packages for different versions of numpy although we don't really need to, as far as I can tell.

The alternative is to install sherpa first, as suggested in the thread you linked. Conda will then stop complaining and will update the numpy version to match the one required by the latest package you install, even if that could break sherpa. Or just install whatever version of numpy you wish, making sure it's the most recent version among the ones supported by the different packages.

I hope this helps, but we'll consider your suggestion either way.

**Comment by cdeil** [comment]
@olaurino - Thanks for your help!

I've split off the question how to select a Fortran compiler in a separate issue: #134

**Comment by cdeil** [comment]
I've also split off the question on Numpy version for the Sherpa conda packages out into a  separate issue: #135

**Comment by olaurino** [comment]
@cdeil is this request still valid? I am asking because it looks like the reasons for your request were:
  - being unable to use the conda packages because of numpy versions conflicts
  - being unable to use a fortran compiler in some setups

Both this issues should be resolved now: the 4.8.0 binaries do not pin the numpy version and should be compatible with 1.8 to 1.10. Also, we are adding documentation to show how to set a fortran compiler that is not in the PATH.

Do you think there is still merit in having a python-only build option?

**Comment by cdeil** [comment]
With Sherpa install getting easier, the advantage of having a Python-only subset build option gets smaller.

I think it would still be valuable to have for users that have install / link errors with some extensions.
It could also make it simpler to get the Python 3 porting going ... start with the easy-to-port pure-Python core, leaving the less-used, hardest to port extensions for later.

But I'm not familiar with the Sherpa build scripts and how much work it would be to implement such an option. So @olaurino, if it's complicated to add and you don't think it's very useful to have, go ahead and close this feature request!

**Comment by olaurino** [comment]
@cdeil, at the moment it is not so much a matter of how hard/simple it is, but rather of how much value it adds.

It should not be hard to implement this option (although most of our tests should be conditionally skipped, leaving very few of them), but it may take a while for this RFE to get high enough in the priority stack to get addressed. On the other hand, your Python 3 point is well taken, and that may make the difference, so this may be part of the Python 3 migration.

I'll take that you think there is still some value in this option. So I'll keep this ticket open and we'll prioritize it.
