### ISSUE TITLE
Numpy version spec for conda package

### ISSUE THREAD

**Issue by cdeil** [sherpa/sherpa#135]
This is a continuation of https://github.com/sherpa/sherpa/issues/133#issuecomment-165149584 .

As discussed at https://github.com/gammapy/gammapy/pull/392#issuecomment-163707574, both for Gammapy continuous integration and for a workshop we did with end users we have Sherpa conda install issues because the Conda recipe pins the Numpy version to 1.7, whereas packages from the Continuum or Astropy conda channel use newer Numpy versions.

The symptoms of the issues are either that:
* `conda install` commands fail, or wildly down- and upgrade Numpy depending on the order of install commands for Sherpa, Astropy and other packages.
* Errors like `ValueError: numpy.dtype has the wrong size, try recompiling` (e.g. here: https://travis-ci.org/gammapy/gammapy/jobs/96029239#L1210) appear during installation or at import time.

I don't fully understand the situation, but I gather there is a possibility that API and ABI compatibility of Numpy 1.X versions is high enough that it might be possible that Sherpa built against one Numpy 1.X version would work for all other Numpy 1.X versions?
If that is the case, then changing the conda spec for the Sherpa packages to not pin the Numpy version would be a simple and great solution, no?

@mwcraig is the Astropy conda channel maintainer and expert and he already commented here:
https://github.com/gammapy/gammapy/pull/392#issuecomment-163973340

@mwcraig - What would be your advice concerning Numpy versions for the Sherpa conda packages?

**Comment by mwcraig** [comment]
Just took a quick look at the sherpa conda channel and the code repo.

@cdeil -- if you install sherpa with: `conda install -c https://conda.anaconda.org/sherpachannel/test  sherpa=4.8` you will get to a conda package compiled without numpy locked. Note well this is on their *test* channel...I'm sure if you try it, find errors, and report them it would be appreciated.

@sherpa -- I still haven't completely figured out, for a compiled package, when the conda package has to be built  and run against the same numpy version and when it doesn't. For cython code I've looked for `cimport numpy`...but sherpa doesn't use cython, so I assume you woould have to look at your C/C++ and see if it calls numpy. If so you should build for all numpy/python combinations continuum supports (within reason). I can help with that later this week if you want. Turns out to be highly automatable.

**Comment by olaurino** [comment]
Thanks @mwcraig. Any help in automating the conda build generation is appreciated. Likewise for understanding how to build against different numpy versions for interoperability.

**Comment by olaurino** [comment]
@cdeil, @mwcraig I just tested the sherpa 4.8.0 binaries with all the numpy versions from 1.8 to 1.10 (downgrading matplotlib and astropy to match) and the tests are OK on Linux64, so I think @cdeil should be fine with the new binaries against any versions on numpy.

@cdeil if you could please confirm I could probably close this issue, at least until the open ended dependency on numpy >1.8 backfires and we need to do something else :)

By the way, we do include numpy in C extensions (at least numpy/arrayobject.h), but I suspect that since we build using numpy 1.8 (and we don't leverage any new features) we get binary compatibility with later versions.

**Comment by mwcraig** [comment]
@olaurino -- the numpy ABI tries to be backwards compatible so you should be good compiling against an older version of numpy. If you want to build against each version of numpy that can be done relatively painlessly with [conda-build-all](https://github.com/scitools/conda-build-all).

If you have a larger set of software you want to build/provide conda packages for, take a look at [conda-builder-affiliated](https://github.com/astropy/conda-builder-affiliated). This is still sorely lacking in docs and will be undergoing a couple changes in the next 48 hours or so, but tries to minimize the overhead in maintaining a set of packages, mainly by auto-generating recipes when possible.

**Comment by olaurino** [comment]
@cdeil could you please confirm this issue is resolved by the new conda binaries for 4.8.0?

Also notice that we moved the binaries from the test channel to the main channel.

**Comment by cdeil** [comment]
@olaurino - Yes, this issue is resolved.

Locally I get `https://conda.binstar.org/sherpa/osx-64/sherpa-4.8.0-py27_2.tar.bz2` and `1.10.2` and the only error is this one, which I think is already being worked on:
```
____ ERROR collecting software/anaconda/envs/py27-gammapy/lib/python2.7/site-packages/sherpa/astro/datastack/tests/test_datastack.py ____
software/anaconda/envs/py27-gammapy/lib/python2.7/site-packages/sherpa/astro/datastack/tests/test_datastack.py:27: in <module>
    from sherpa.astro import datastack
software/anaconda/envs/py27-gammapy/lib/python2.7/site-packages/sherpa/astro/datastack/__init__.py:269: in <module>
    import matplotlib.pyplot as plt
E   ImportError: No module named matplotlib.pyplot
```

For Gammapy CI @bsipocz is also switching to Sherpa 4.8 for testing:
https://github.com/gammapy/gammapy/pull/428
She's also adding a test build on Mac and with the git master version.

For Gammapy it would be useful to have regular (e.g. weekly) Sherpa dev conda packages available, both for testing and for users, because the release cycle for Sherpa is ~ 1 year, right?
@olaurino - Is it useful if I make a new issue with this feature request, or is that anyways on your radar to set that up in the future?

**Comment by olaurino** [comment]
@cdeil are you still interested in dev conda packages for Sherpa? I have been working on that, so it might happen in the not so distant future.

**Comment by cdeil** [comment]
@olaurino - Thank you.

In Gammapy, we also have a build where we test against latest development version of Numpy and Astropy, and every few months, a regression does occur and we can resolve it straight away. Usually it's bad code in Gammapy, but sometimes a real regression in upstream Astropy or Numpy.

So yes, I still think it would be very useful to have and add this for Sherpa for us.
