### ISSUE TITLE
Explanations about TableModel

### ISSUE THREAD

**Issue by tibaldo** [sherpa/sherpa#142]
I am working on a project for which I need to use arbitrary non-arithmetic spectral models. Therefore, I am planning to use TableModel. To make sure I understand how to use it properly, I did an exercise using a test dataset and comparing the predicted counts (from the plot_model method) between a sherpa powlaw1d model with gamma 2 and a TableModel that I constructed as follows. I took as x values for TableModel the energy boundaries of the arf file, and I calculated the y values as y=N*(x/E0)^-g (I took E0 the same as ref in sherpa powlaw1d). As you can see in the attached plots, the predicted counts look different if I use g=2 for the TableModel, but they are consistent for g=1 (I tweaked the normalization so that the number of counts in the peak is approximately the same for easier visual comparison). I verified that this does not depend on the x grid used for TableModel (for a 10 times finer grid the results are the same). Hence, I cannot figure out why the spectral indices are different between sherpa powlaw1d and the simple arithmetic formula. Probably I misunderstand something about TableModel or powlaw1d. Any explanations or suggestions are appreciated, thanks!
![model_powlaw1d-2](https://cloud.githubusercontent.com/assets/3046743/12194793/c3c4f16e-b5f2-11e5-9019-7511105b58f1.png)
![model_table-1](https://cloud.githubusercontent.com/assets/3046743/12194795/c61574e8-b5f2-11e5-9006-2d6c469263f2.png)
![model_table-2](https://cloud.githubusercontent.com/assets/3046743/12194798/c8277a7e-b5f2-11e5-824d-d6f66300830b.png)

**Comment by tibaldo** [comment]
Sorry, file names disappeared: top is powlaw1d with gamma=2, mid panel is TableModel with g=1, and bottom TableModel with g=2.

**Comment by DougBurke** [comment]
The table models do need better documentation! I think the issue here is that you need to calculate the integral of the model over the bin, so that the y values are in count/s rather than count/s/keV. The plots are automatically converted from count/s to count/s/keV. This is all assuming an integrated dataset (Data1DInt or DataPHA) rather than Data1D.

You should be able to overplot the models on the same graph - assuming you have them set up for datasets 1, 2, and 3 (with different combinations of model and g values):

    plot_model()
    plot_model(2, overplot=True)
    plot_model(3, overplot=True)

As an aside: the table model actually supports two forms of table model

* a simple grid that can be scaled by a normalization, as you are using here

* XSPEC table models (additive/atable and multiplicative/mtable) if you have compiled in the XSPEC table models. This allows you to have multiple parameters, but is more complicated to set up the needed data.

**Comment by tibaldo** [comment]
Thanks for the explanations. What is the integration range? The TableModel has the same number of x and y points, so I assumed it was differential flux at the energy given by each x node. Or do I need to have one more x value so that the x values represent the energy bounds of the integration ranges?

**Comment by DougBurke** [comment]
So, it looks like the table model code isn't really expecting an "integrated" model, as it looks like it only expects two columns (x and y). So I suggest using the mid-point of the bin for the X value and integrate over the bin for the Y value. So, with the following FITS file, which represents a power law (i.e. `powlaw1d`) with gamma=2, ampl=1, ref=1 where the `mdl` column is integrated over the bin

```
% dmlist pl_gamma2.fits"[#row=1:10]" data,clean
#  elo                  ehi                  emid                 mdl
                 0.10                0.110               0.1050     0.90909090909091
                0.110                0.120               0.1150     0.75757575757576
                0.120                0.130               0.1250     0.64102564102564
                0.130                0.140               0.1350     0.54945054945055
                0.140                0.150               0.1450     0.47619047619048
                0.150                0.160               0.1550     0.41666666666667
                0.160                0.170               0.1650     0.36764705882353
                0.170                0.180               0.1750     0.32679738562091
                0.180                0.190               0.1850     0.29239766081871
                0.190                 0.20               0.1950     0.26315789473684
...
                 9.90                9.910               9.9050       0.000101927448
                9.910                9.920               9.9150      0.0001017219492
                9.920                9.930               9.9250      0.0001015170711
                9.930                9.940               9.9350      0.0001013128114
                9.940                9.950               9.9450      0.0001011091676
                9.950                9.960               9.9550      0.0001009061371
                9.960                9.970               9.9650      0.0001007037176
                9.970                9.980               9.9750      0.0001005019065
                9.980                9.990               9.9850      0.0001003007015
                9.990                 10.0               9.9950      0.0001001001001
```
I can read these into Sherpa (I'm using the CIAO 4.8 version but the same should work using standalone, although the changes to the plot will have to be replaced by equivalent matplotlib calls):

```
% sherpa
-----------------------------------------------------
Welcome to Sherpa: CXC's Modeling and Fitting Package
-----------------------------------------------------
CIAO 4.8 Sherpa version 1 Thursday, December 3, 2015

sherpa-1> dataspace1d(0.1, 10, 0.01, dstype=Data1DInt)
sherpa-2> dataspace1d(0.1, 10, 0.01, id='tbl', dstype=Data1DInt)
sherpa-3> set_source(1, powlaw1d.pl)
sherpa-4> pl.gamma = 2
sherpa-5> plot_model(1)
sherpa-6> log_scale()
sherpa-7> set_curve(['*.color', 'default'])
sherpa-8> load_table_model('tblpl', 'pl_gamma2.fits', colkeys=['emid', 'mdl'])
sherpa-9> set_source('tbl', tblpl)
sherpa-10> plot_model('tbl', overplot=True)
sherpa-11> set_curve(['line.style', 'dot'])
sherpa-12> print_window('plot_int.png')
```

![plot_int](https://cloud.githubusercontent.com/assets/224638/12199454/4a77dfe4-b5e6-11e5-9700-8fc0b76cf0e4.png)

As can be seen the two lines are very similar. I don't know if the differences are because of interpolation used by the table model or if using the EMID column here is wrong (my guess is the interpolation, but I haven't tracked through the code).

As a check, I try out the "non-integrated" case (where the only difference is using `Data1D` rather than `Data1DInt`):

```
% sherpa
-----------------------------------------------------
Welcome to Sherpa: CXC's Modeling and Fitting Package
-----------------------------------------------------
CIAO 4.8 Sherpa version 1 Thursday, December 3, 2015

sherpa-1> dataspace1d(0.1, 10, 0.01, dstype=Data1D)
sherpa-2> dataspace1d(0.1, 10, 0.01, id='tbl', dstype=Data1D)
sherpa-3> set_source(1, powlaw1d.pl)
sherpa-4> pl.gamma = 2
sherpa-5> plot_model(1)
sherpa-6> log_scale()
sherpa-7> set_curve(['*.color', 'default'])
sherpa-8> load_table_model('tblpl', 'pl_gamma2.fits', colkeys=['emid', 'mdl'])
sherpa-9> set_source('tbl', tblpl)
sherpa-10> plot_model('tbl', overplot=True)
sherpa-11> set_curve(['line.style', 'dot'])
sherpa-12> print_window('plot_nonint.png')
```
![plot_nonint](https://cloud.githubusercontent.com/assets/224638/12199563/05943f16-b5e7-11e5-908e-b4f3e9815ef0.png)

The table model displays the same values (the red line) - as expected - but in this case the power-law model from Sherpa is higher by a factor of 100 - since now the model values are not being multiplied by the bin width (which is 0.01).

**Comment by DougBurke** [comment]
Just to note that it looks like when using `astropy` (or `pyfits` - but don't use this ;-) for I/O, the table model has to be in ASCII format [*]. So from the example above the `emid` and `mdl` columns would need to be written out to a simple two-column ASCII file - e.g.

```
# emid mdl
1.0500000000000e-01 9.0909090909091e-01
1.1500000000000e-01 7.5757575757576e-01
1.2500000000000e-01 6.4102564102564e-01
1.3500000000000e-01 5.4945054945055e-01
...
9.975000000000 1.0050190652117e-04
9.985000000000 1.0030070150310e-04
9.995000000000 1.0010010010010e-04
```

[*] I don't know if this is due to the existing known issues with the astropy backend code, for which there are PRs, or there's a different issue.

**Comment by tibaldo** [comment]
Thanks for the tip of passing integrated fluxes rather then differential ones. I played more with analytical functions vs table and I found out that to obtain correct results with table model:
- the y values need to be integrated fluxes over the same energy ranges as the dataset
- the x values need to be the lower bounds of the bins (not the mean as suggested above).
Please, let me know if I am mistaken. Otherwise I hope this helps clarifying the documentation.
