### ISSUE TITLE
DataPHA and the bin_lo/hi fields: what are they?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1471]
There's no explicit documentation about these fields, so I'm guessing here.

```
sherpa-4.14.0> load_pha("tgcat/pha2")
WARNING: systematic errors were not found in file 'tgcat/pha2'
statistical errors were found in file 'tgcat/pha2'
but not used; to use them, re-read with use_errors=True
read background_up into a dataset from file tgcat/pha2
read background_down into a dataset from file tgcat/pha2
Multiple data sets have been input: 1-12

sherpa-4.14.0> data = get_data(3)

sherpa-4.14.0> print(data)
name           = tgcat/pha2
channel        = Float64[8192]
counts         = Float64[8192]
staterror      = None
syserror       = None
bin_lo         = Float64[8192]
bin_hi         = Float64[8192]
grouping       = None
quality        = None
exposure       = 88727.976992703
backscal       = 1.0
areascal       = 1.0
grouped        = False
subtracted     = False
units          = channel
rate           = True
plot_fac       = 0
response_ids   = []
background_ids = [1, 2]

sherpa-4.14.0> get_arf(3)
IdentifierErr: ARF data set 1 in PHA data set 3 has not been set

sherpa-4.14.0> get_rmf(3)
IdentifierErr: RMF data set 1 in PHA data set 3 has not been set
```

So, we can see that reading in a Chandra HETG/METG dataset frmo a PHA2 file we get the `bin_lo` and `bin_hi` fields. They appear to be there so we can do a "response-less" display and/or fit (i.e. we have no response but we can still change to wavelength/energy for plots).

```
sherpa-4.14.0> data.units
'channel'

sherpa-4.14.0> set_analysis(3, "wave")

sherpa-4.14.0> data.units
'wavelength'

sherpa-4.14.0> plot_data(3)
```

![download1](https://user-images.githubusercontent.com/224638/158889683-fad3e250-465d-426e-8201-8a8396fed7ae.png)

```
sherpa-4.14.0> plt.savefig("/home/dburke/download1.png")

sherpa-4.14.0> set_analysis(3, "energy")

sherpa-4.14.0> data.units
'energy'

sherpa-4.14.0> plot_data(3)
```

![download2](https://user-images.githubusercontent.com/224638/158889719-ce3b99f8-2793-4a97-aeeb-4bdc919c05cb.png)

I assume that we have to have the same number of elements as the channels array, but there are some tests which use a different size. These are low-level tests and I believe are essentially checking that things work, and there's no reason not to use a matching array size, but I have not looked into this in depth.

This is in the context of #1470

**Comment by hamogu** [comment]
I can confirm that that's the purpose of writing the bin_high, bin_lo columns as written by `tgextract` (see https://cxc.cfa.harvard.edu/ciao/ahelp/tgextract.html#plist.outfile_type). In real files, the number of entries in those column will always match the number of channels, I would argue that it's a bug to accept anything else.

At this point, we can decide what we want to do with such "ancillary information". Drop it because it's not in the OGIP standard? I have had the following suggestion in mind for a while, but I think the only place where I write it down is a comment in the google doc on binning.

Data objects (in particular DataPHA objects, but really any Data object) have the independent axis, which set the size of the objects (picking up the idea from @DougBurke in #1470). Then there is dependent data and that can be anything that has the same size as the independent axis, e.g. flux, staterror, syserror, bin_low, anything).

That could be handled like this (conceptually, pseudo-code):

```
dependents = {'y': np.array..., 'staterr': np.array...., 'other_propoperty_sherpa_knows_nothing_about': np.array....}
```
Sherpa would make use of those arrays with specific names that is knows about (x, staterr), but all the rest can be ust carried along for the ride.

Each one of them would have a specific "summarize_function" that is called when several channels / bins are through in one group., e.g.
```
summarize_funcs = {'y': np.mean, 'staterr' : lambda x:np.sqrt((x**2).sum()), 'bin_low': np.min, ...}
```
and then a `get_XXXX(filter=True/false, group=True`) would do 
```
dep = dependens[XXXX]
func = summarize_fincs[XXXX]
return np.array([func(dep[bins[0]: bins[1]) for bin in bins])
```

We can describe all existing fields in that way, and seamless add more any time (e.g. quality). It's mostly a question of wirting the right summarize_func for e.g. quality arrays.
