### ISSUE TITLE
Sherpa plot classes should use `super()`

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1487]
The Sherpa plot objects contain a lot of code like this:
```
class SomePlotType(ModelPlot):
    def plot(self, ...):
        Plot.plot(x, y, ....)
```
e.g. https://github.com/sherpa/sherpa/blob/main/sherpa/plot/__init__.py#L865

In this case, `ModelPlot` derives from `Plot` and does not itself change the behaviour of the `plot` method. We should investigate if using `super().plot(...)` is possible. The current structure obscures the inheritance and leads to some duplication.

I've come across this in implementing #1382. In #1375 I had defined a slightly simplified API, which requires just a handful of changes in the Sherpa plot classes. I want to limit changes in the plot classes to what is absolutely necessary to match the API in #1375 and thus open this issue to keep track.

**Comment by DougBurke** [comment]
I've been randomly making changes to use super throughout the code base (the Data classes are a special case where it's not always possible) as I note them. So at some level this is a general issue, but it's useful to carve out module/functionality changes.

**Comment by DougBurke** [comment]
Just to mention that I have seen some problems switching to using super for models that use multiple inheritance. I can no longer remember what the problems were or what classes were involved ,but thought I'd mention it.

**Comment by DougBurke** [comment]
After working on this for 

- #1679
- #1988
- #1989

I'm reminded on what the problems are (or partly are): we have some subclasses that implement both "point" and "histogram" options and so the choice of what superclass to use needs to be explicit rather than just inferred (and probably done in a non-MRO order for reasons).

Once some / all of these listed PRs get merged I suggest closing this ticket.

**Comment by hamogu** [comment]
Sure, let's close it.
