### ISSUE TITLE
Consider allowing type annotations in newly written code

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#1501]
[PEP 484](http://www.python.org/dev/peps/pep-0484) introduced type annotation for functions and methods and [PEP 526](http://www.python.org/dev/peps/pep-0526) added a similar syntax for variables and attributes.

Type annotations at this point are completely optional, Python itself does nothing with that information. However, it 

- provides additional documentation for developers
- enables the use of static type checkers at compile time such as http://mypy-lang.org/
- can be used to generate parts of the docstrings ([implemented in napoleon](https://github.com/sphinx-doc/sphinx/blob/master/doc/usage/extensions/napoleon.rst#type-annotations) and [under discussion in numpydoc](https://github.com/numpy/numpydoc/issues/196))

Numpy has been adding a lot of type annotations to its code in the last few releases as well as appropriate types to describe numpy arrays etc. (https://numpy.org/devdocs/reference/typing.html) 

I suggest that we try to get into the habit of adding type annotations in new code when it's not too hard (i.e. for cases when it's just str, float etc) in the future, but don't spend effort to convert existing code.

**Comment by DougBurke** [comment]
I was just looking at doing this, but I know there are ongoing changes (e.g. simplifications in Python 3.9 or 3.10) so working out what is and isn't appropriate needs some thought. For instance, we have a lot of code that takes objects that we currently hard-code knowledge of rather than rely on duck typing (e.g. something derived from ArithmeticModel) and what is the best solution here (treat as Any, or as ArithmeticModel, or something else).

My particular play-around got as far as something like (I don't guarantee the following is syntactically correct, and definitely no  comment on semantically correct) but then I started reading about `collections.abc` and then working out whether I needed `MutableMapping` instead and realised I had a bug to work on instead!

```
from typing import Mapping, Tuplle
InterpolationScheme = Tuple[TemplateModel, Dict[Any, Any]]
InterpolationMap = Mapping[str, InterpolationScheme]

interpolators : InterpolationMap = {}
```

I also think we'd require that we actually have some way to check that the annotations are sensible (via running the code with whatever-system-makes sense) to make sure we just aren't adding noise.

**Comment by hamogu** [comment]
There is a lot of development still happening on that front: https://docs.python.org/3.11/whatsnew/3.11.html
so it might be too early to embrace; it's worth keeping an eye on though.

**Comment by DougBurke** [comment]
Out of interest I just tried adding some type annotations to new code in `sherpa/ui/utils.py` and I never got `mypy` to run on it (I couldn't be bothered to wait). So there may be some issues because some of our files are a tad large.

On the plus side I did seem able to create code to type check a type-constrained dataclass acting a bit like a dict (when I pulled the new code out into a separate file), so that's nice.

**Comment by DougBurke** [comment]
One interesting (for a very specialized meaning of the word interesting) issue is that we might want to tweak the code that pulls the Session methods out and creates "top-level" functions, since I have a case where I've annotated a sherpa.ui.utils.Session method:

```
>>> from sherpa.ui.utils import Session
>>> help(Session.get_default_id)
Help on function get_default_id in module sherpa.ui.utils:

get_default_id(self) -> Union[int, str]
    Return the default data set identifier.
    
    The Sherpa data id ties data, model, fit, and plotting
    information into a data set easily referenced by id. The
    default identifier, used by many commands, is returned by this
    command and can be changed by `set_default_id`.
    
...
```

but note that this annotation is not copied over (as I wouldn't really expect it to, as the code was written well-before annotations were added) to the "top-level" routine:

```
>>> from sherpa import ui
>>> help(ui.get_default_id)
Help on function get_default_id in module sherpa.ui:

get_default_id()
    Return the default data set identifier.
    
    The Sherpa data id ties data, model, fit, and plotting
    information into a data set easily referenced by id. The
    default identifier, used by many commands, is returned by this
    command and can be changed by `set_default_id`.
...
``` 

This can be seen as a selling point - we can add these annotations without worrying about how it might affect the CIAO user ;-)

**Comment by hamogu** [comment]
We're doing this now in practice where useful, so no need to keep this issue open.
