### ISSUE TITLE
building error using pip

### ISSUE THREAD

**Issue by StefanoRapisarda** [sherpa/sherpa#1528]
Hi guys,

I am trying to install sherpa via pip (I manage my python versions via pyenv so I would prefer this over conda), but I get the following error:

`ERROR: Could not build wheels for sherpa, which is required to install pyproject.toml-based projects`

Python version 3.9.11, macOS Monterey (12.3.1), pip 22.1.1. Any idea what is going on and how can I solve this? Thanks.

**Comment by hamogu** [comment]
Can you post the full output that you get? I install sherpa with pip all the time and I have never seen this error message. Do you install with pip from pypi or did you clone the github repro and use the local code checkout with `pip install .` in the sherpa directory?

For example, I build sherpa about an hour ago with 
`pip install sherpa` and I'm on MacOS 12.4, Python 3.10, pip 21.3.1. That's no exactly the same as you, but pretty close, so I suspect that it's the version of pip or something else in the environment that's different, e.g. you might try to upgrade or downgrade pip and wheel:
`pip install --upgrade pip setuptools wheel`

Please let us know what you find so that we can track this down, and see if there is, e.g. an update to our pyptoject.toml that we can do to avoid this.

**Comment by hamogu** [comment]
Oh, and are you on an ARM chip or this this a Mac with an Intel chip? It might not matter, but I don't know for sure. Sherpa itself compiles on M1, but mismatches e.g. a numpy compiled for Intel in an environment that compiles for ARM could cause strange errors, too.

**Comment by StefanoRapisarda** [comment]
I install with pip from pypi and I am on an Intel chip. As you suggested, I updated pip and wheel, but I get the same error. Attached you find my output.
[sherpa_error_output.txt](https://github.com/sherpa/sherpa/files/8785518/sherpa_error_output.txt)

**Comment by hamogu** [comment]
Please try to set `export CFLAGS='-Wno-implicit-function-declaration'`. That seems to be needed to build with clang (but not with gcc). I already have a PR open to change that in the docs : https://github.com/sherpa/sherpa/pull/1522 because I run into that, too. Instead, we discovered that a files that should not have been added, was accidentially added to the source tree, so that should also fix it (https://github.com/sherpa/sherpa/pull/1523), but only if you use the most recent checkout from github.

And, just to check, you also need to see `export PYTHON_LDFLAGS=' '` on MacOS - see https://sherpa.readthedocs.io/en/4.14.1/install.html - Your error message indicates is the no-implicit-function-declaration flag that's missing, but I just want to make sure you don't just solve that problem and then run into the next.

**Comment by StefanoRapisarda** [comment]
Thank you very much, that worked!

**Comment by cxl4444** [comment]
Hello,

When I install sherpa with pip, I also encounter the same problem. I upgrade pip and wheel, and set export CFLAGS='-Wno-implicit-function-declaration', but they does not work.

Python version 3.10.6, macOS Monterey (12.6), pip 22.3, M1 chip.

The output is as follow:

(astronomy) cxl-2:~ cxl$ pip3 install sherpa
Collecting sherpa
  Using cached sherpa-4.15.0.tar.gz (13.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /opt/homebrew/Caskroom/miniforge/base/envs/astronomy/lib/python3.10/site-packages (from sherpa) (1.23.4)
Building wheels for collected packages: sherpa
  Building wheel for sherpa (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for sherpa (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running sherpa_config
      warning: sherpa_config: built configure string ['./configure', '--prefix=/private/var/folders/qq/ptr4tj3j52d719r0qmjgspdw0000gn/T/pip-install-fyqrr1ui/sherpa_175da724be304d6185636cd88beeb71b/build', '--with-pic', '--enable-standalone', '--disable-maintainer-mode', '--enable-stuberrorlib', '--disable-shared', '--enable-shared=libgrp,stklib', '--enable-fftw', '--enable-region', '--enable-group', '--enable-stk', '--enable-wcs']
      
      checking for a BSD-compatible install... /usr/bin/install -c
      checking whether build environment is sane... yes
      checking for a thread-safe mkdir -p... ./install-sh -c -d
      checking for gawk... gawk
      checking whether make sets $(MAKE)... yes
      checking whether make supports nested variables... yes
      checking whether to enable maintainer-specific portions of Makefiles... no
      checking build system type... Invalid configuration `arm64-apple-darwin20.0.0': machine `arm64-apple' not recognized
      configure: error: /bin/sh ./config.sub arm64-apple-darwin20.0.0 failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sherpa
Failed to build sherpa
ERROR: Could not build wheels for sherpa, which is required to install pyproject.toml-based projects

**Comment by hamogu** [comment]
@cxl4444 : Just to check, you also need to set export PYTHON_LDFLAGS=' ' on MacOS - see https://sherpa.readthedocs.io/en/4.14.1/install.html 

Also, can you do "gcc --version" on the command line and let me know what you get?

**Comment by hamogu** [comment]
It works for me, but with two differences: I did **not** use `CFLAGS='-Wno-implicit-function-declaration'` since that should no longer be necessary in 4.15.0 (the github issues you posted to is older and about 4.14.1), see https://sherpa.readthedocs.io/en/4.15.0/install.html and I don't use homebrew. I did test on an M1 in a conda environment with python 3.10 on MacOS Monteray and pip 22.3, so that's as close as I get to your setup. I suspect that homebrew gives you a non-standard compiler or a different library than the system versions of MacOS or something like that. 

Can you try without `CFLAGS='-Wno-implicit-function-declaration'` , but with `PYTHON_LDFLAGS=' '` instead? Also, let us know what compiler (`which gcc`) you use and I hope we can spot the difference from there.

**Comment by cxl4444** [comment]
I just follow your suggestion to rerun the command for sherpa==4.15.0 and 4.14.1, but it is not work. 

(astronomy) cxl-2:~ cxl$ gcc --version
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

(astronomy) cxl-2:~ cxl$ which gcc
/usr/bin/gcc

I have no idea about why the Target is x86_64, rather than arm64. And I try to change the complier installed by homebrew, using the command "alias gcc='gcc-12'". It is also not work.

**Comment by cxl4444** [comment]
I change the gcc Target to  'arm64-apple-darwin21.6.0' by switch off the Rosetta option.

Now the output of 'gcc --version' and 'which gcc' are

(astronomy) cxl-2:~ cxl$ gcc -v
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

(astronomy) cxl-2:~ cxl$ which gcc
/usr/bin/gcc

But I notice the Target is 'arm64-apple-darwin21.6.0', rather than 'arm64-apple-darwin20.0.0'.
Does this lead to the failure?
