### ISSUE TITLE
Use conda-forge to supply conda packages

### ISSUE THREAD

**Issue by maxnoe** [sherpa/sherpa#1625]
This would make use of the great infrastructure conda-forge provides and will probably much simplify the build of conda packages for the project.

It will also make it rather easy to provide builds for e.g. macos arm 64 (M1 / M2 macs)

I can offer some help if you are interested

**Comment by hamogu** [comment]
Thanks for your offer of support!

The problem in providing ARM support is not the lack of upstream packages on anaconda, it's stems form the fact the sherpa fills two roles: It's a stand-alone Python package, but it's also part of the Chandra data analysis system CIAO. Parts of the HEASOFT library (used for the XSPEC models that Sherpa ships with in the CIAO install) does not yet build on ARM. The HEASOFT developers are working on that, but as long as we don't have that, we can't build Sherpa on ARM for all scenarios (as part of CIAO and as a stand-alone program) that we need to support. 

Another problem is the CALDB - when Sherpa is distributed as part of CIAO, we need the Chandra CALDB which is rather large (> 1 GB). conda-forge typically does not host large datasets as conda packages, but the Chandra X-ray Center has always done so, since the CALDB is needed to reduce Chandra data.

We looked at conda-forge, but together these issues make is easier to provide conda packages on a channel that's hosted by the Chandra X-ray Center (CXC) instead of distributing through conda-forge (and releasing it one way is easier than releasing CIAO and stand-alone Sherpa in different ways). However, the next version of Sherpa to be released with CIAO 4.15 is built using conda-forge packages for upstream dependencies (Python, numpy, ...). 

That said, we always welcome user feedback and PR with code contributions; if you are willing to help in other areas that would be very welcome!

**Comment by maxnoe** [comment]
Ok, I see, thanks for the update.

> The problem in providing ARM support is not the lack of upstream packages on anaconda, it's stems form the fact the sherpa fills two roles: It's a stand-alone Python package, but it's also part of the Chandra data analysis system CIAO. 

I see. But wouldn't conda-forge be an appropriate channel for the stand-alone package and simplify that part?

> Another problem is the CALDB - when Sherpa is distributed as part of CIAO, we need the Chandra CALDB which is rather large (> 1 GB).

That could be handled in a similar way e.g. to what conda-forge is doing with matplotlib:
there is a `matplotlib-base` package, that does not depend on all the optional dependencies (i.e. qt for showing interactive plots) and a `matplotlib` package depending on `matplotlib-base` and the optional dependencies. 

I.e. you could offer `sherpa` through conda-forge, and `chandra-caldb` through your own infrastructure that supports these large file sizes?

**Comment by hamogu** [comment]
> I.e. you could offer sherpa through conda-forge, and chandra-caldb through your own infrastructure that supports these large file sizes?

We could, but then we would have to maintain things on both. That's extra work for us that we'd rather invest into other developments.
