### ISSUE TITLE
How to select / run Sherpa tests during development?

### ISSUE THREAD

**Issue by cdeil** [sherpa/sherpa#167]
I'd finally like to start contributing to Sherpa by taking a stab at #150.

Would it be possible to extend the info on how to hack on Sherpa, maybe here?
https://github.com/sherpa/sherpa/blob/master/CONTRIBUTING.md#checklist-for-contributed-code

In Astropy my workflow is that I edit files in the git repo and then run tests repeatedly like this:
```
python setup.py test [options for test selection, reporting]
```
I think this runs this in the background:
```
python setup.py build_ext -i
```

I have a setup with Macports where this is working for me with Sherpa:
```
python setup.py install --user
cd /tmp # leave sherpa repo so that the installed version is picked up
sherpa_test # run tests from installed version
cd - # go back to Sherpa repo
```

- Is it possible to run the tests from the git repo, without having to cd away?
- How can I select which tests to run?

(Apologies if I've asked this before! I don't remember ...)

This is not working for me:
```
$ python2.7 setup.py test
running sherpa_config
warning: sherpa_config: built configure string['./configure', '--prefix=/Users/deil/code/sherpa/build', '--with-pic', '--enable-standalone', '--disable-maintainer-mode', '--enable-stuberrorlib', '--disable-shared', '--enable-shared=libgrp,stklib', '--enable-fftw', '--enable-region', '--enable-group', '--enable-stk', '--enable-wcs']

running xspec_config
running develop
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/test-easy-install-60417.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.
```

**Comment by DougBurke** [comment]
I use conda environments, in which I can do

    python setup.py develop
    python setup.py test

Perhaps there's something we've missed in the recent changes @olaurino has made to the build based on your reports that is causing the failure here. I am also working on a linux machine, so could it be an OS-X/framework related issue with our setup?

There are subtle differences between

    python setup.py test

and

    sherpa_test

(and in fact the environment in which the test is run) which I've recently tripped up (i.e. my tests pass but those on Travis-CI, which exercise the different paths has flagged up) and don't fully understand.

**Comment by olaurino** [comment]
I am out today. As I am going to be traveling for most of this week, I'll try to take a look tonight. In the meantime, and in case I am not able to respond, you can try and change the aliases defined in setup.cfg and adapt them to your environment.

**Comment by olaurino** [comment]
> In Astropy my workflow is that I edit files in the git repo and then run tests repeatedly like this:
> 
> python setup.py test [options for test selection, reporting]
> I think this runs this in the background:
> 
> python setup.py build_ext -i

This is what I do with Sherpa as well, with one catch I'll list below. But first:

> I have a setup with Macports where this is working for me with Sherpa:
> 
> python setup.py install --user
> cd /tmp # leave sherpa repo so that the installed version is picked up
> sherpa_test # run tests from installed version
> cd - # go back to Sherpa repo

`sherpa_test` is supposed to work both with binaries and source distributions. However, if you are working with source distributions (with our without git) you should be able to use `python setup.py test`, and have more control, which is what we do as well.

So:

> Is it possible to run the tests from the git repo, without having to cd away?

Yes, and there are at least two ways of doing so, each with a number of options:

  - `python setup.py test`. `test` is a wrapper that invokes `py.test`, which is listed as a dependency in `setup.py` and should be installed automatically if not already present. `test` is also an alias in `setup.cfg` that ensures `sherpa_config` and `xspec_config` are also run. The catch is in the assumption here that one is using `develop` as a command when they want to develop, which means that some setups like yours (`install --user`) may not work. However, one of the reasons why I chose aliases rather than hard-coding these commands, is that aliases should be configurable by the user. See: https://pythonhosted.org/setuptools/setuptools.html#alias-define-shortcuts-for-commonly-used-commands and https://pythonhosted.org/setuptools/setuptools.html#configuration-file-options. So, you should have full control over the commands that are run using standard setuptools patterns, including overriding our defaults and aliases... our defaults/assumption also work (or are supposed to work, modulo bugs) if you have a setup where `develop` works.

  - directly using `py.test`. At this point in time, `py.test` is just used for tests discovery (we are evaluating whether to use `py.test` features and get locked in, but that has implications on CIAO so we are following CIAO policies for this change to happen). For you this means that you can use anything able to select/run unittests following the standard python conventions for test discovery, including `py.test` itself.

In practice, if "our" `test` command works for you, you can simply pass it arguments you would pass to `py.test` itself: if you just want to select a test, for instance:

> python setup.py test -a "sherpa/tests/test_sherpa.py::test_sherpa::test_reading_floats"

You can use `--pytest-args=` instead of `-a`.

If "our"  `test` alias does not work for you, you could either override it with e.g. `python setup.py alias --global-config test sherpa_config xspec_config test`; then you should still be able to pass arguments to `py.test` with `-a` or `--pytest-args=`. Or, you could just use `py.test` according to its docs: http://pytest.org/latest/usage.html

Note that Sherpa comes with a `pytest.ini` file. If you don't like its defaults, you have a number of options: you could change it and make git ignore it with the `update-index --assume-unchanged` command (see https://git-scm.com/docs/git-update-index). Or you can override sherpa's `pytest.ini` defaults from the command line. Probably there are more options, and you can combine aliases and py.test overrides.

I tried to describe the above options in a manner that might be reused in the Readme or Contributing files. However, the goal was to give Sherpa customized commands within standard frameworks, and to give the user the power to use those standard frameworks to override our defaults.

It doesn't mean, of course, that there may not be bugs, neither that our choices were necessarily the best given the available options. But that was the general idea.

Please let me know if you have any other questions, or if any of the above does not work for you or does not solve your problem.

**Comment by cdeil** [comment]
@olaurino - Thanks for the infos. Using `py.test` from the git working directory works ... wonderful!!!

`py.test` is currently not mentioned in the README and CONTRIBUTING, basically the info from your last comment here should be added somewhere so that other potential contributors can easily find it.
