### ISSUE TITLE
redshift range hard-coded in table models 

### ISSUE THREAD

**Issue by JohannesBuchner** [sherpa/sherpa#1814]
In sherpa '4.15.0', loading a atable with load_table_model adds a redshift parameter, with hard-coded hard limits z=0-5. I would like to allow higher redshifts.

It seems difficult to work around this. In earlier sherpa versions one could override hard_max.

`__setattr__` disallows replacing the redshift parameter.

**Comment by anetasie** [comment]
@JohannesBuchner could you provide an example of the model you are loading? Thanks!

**Comment by JohannesBuchner** [comment]
This is with atable [uxclumpy-cutoff.fits](https://zenodo.org/record/1169181/files/uxclumpy-cutoff.fits?download=1)

**Comment by hamogu** [comment]
You can still do the same thing in principle, but it's just better hidden. Instead of providing direct access, you need to change `_hard_min`, which is the variable that holds the numerical value of the hard max.

```Python
sherpa In [1]: load_table_model(modelname='atab', filename='/Users/guenther/Downloads/uxclumpy-cutoff.fits')

sherpa In [2]: atb = atab()

sherpa In [3]: atb.redshift = 25
ParameterErr: parameter atab.redshift has a maximum of 5

sherpa In [4]: atb.redshift._hard_max = 500

sherpa In [5]: atb.redshift.max = 500

sherpa In [6]: atb.redshift = 25
```

Why do we make this so hard and why is the hard_max set to such a small (for a redshift) value? I would have expected that to be 1e38 or something like that, but I'm sure @DougBurke has better insight where the number "5" comes from in this case.

**Comment by JohannesBuchner** [comment]
Thanks for the workaround, I will try it!

**Comment by DougBurke** [comment]
Just getting back up to speed after my vacation. I haven't looked at the file yet (it's taking a while to download) but I can say - please use `load_xstable_model` rather than `load_table_model` - as I hope to remove support for XSPEC tables from it at some point - e.g. see the note in https://sherpa.readthedocs.io/en/4.15.1/ui/api/sherpa.astro.ui.load_table_model.html

**Comment by DougBurke** [comment]
So, the XSPEC documentation is rather vague on what it expects for the `redshift` model parameter - https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/general/ogip_92_009/node3.html just says whether we add one, not what the limits are - so I need to check on an actual XSPEC installation what it does. 

The Sherpa code is

https://github.com/sherpa/sherpa/blob/767f516b929f7f53ae256a4902edd27fec4303b4/sherpa/astro/xspec/__init__.py#L1297-L1300

It uses `XSBaseParameter` rather than `XSParameter` because there have  been problems with table models which set parameters to default to a value outside their valid range, and others where setting a parameter wrong can crash everything. It strikes me that we can likely change the redshift parameter from `XSBaseParameter` to `XSParameter`, but it's been a while since I looked at this so would need to check.

**Comment by DougBurke** [comment]
So, with XSPEC 12.13.1 reading in an additive model with `ADDREDSHIFT` header keyword, which indicates that redshift should be included, gives us

```
XSPEC12>mo atable{borus02_v170323a.fits}

Input parameter value, delta, min, bot, top, and max values for ...
              2       0.05(      0.02)        1.4       1.45       2.55        2.6
1:borus02:PhoIndex>
            300          5(         3)         20         50        500       2000
2:borus02:Ecut>
             24        0.1(      0.24)         22      22.25         25       25.5
3:borus02:logNHtor>
            0.5       0.05(     0.005)        0.1       0.15        0.9          1
4:borus02:CFtor>
            0.5       0.05(     0.005)    0.04999        0.1        0.9    0.95001
5:borus02:cos(thInc)>
              1       0.05(      0.01)     0.0999        0.2          5         10
6:borus02:A_Fe>
              0     -0.001(     0.001)          0          0          5          5
7:borus02:z>
              1       0.01(      0.01)          0          0      1e+20      1e+24
8:borus02:norm>

========================================================================
Model atable{borus02_v170323a.fits}<1> Source No.: 1   Active/On
Model Model Component  Parameter  Unit     Value
 par  comp
   1    1   borus02    PhoIndex            2.00000      +/-  0.0          
   2    1   borus02    Ecut       keV      300.000      +/-  0.0          
   3    1   borus02    logNHtor            24.0000      +/-  0.0          
   4    1   borus02    CFtor               0.500000     +/-  0.0          
   5    1   borus02    cos(thInc)          0.500000     +/-  0.0          
   6    1   borus02    A_Fe       A_Sun    1.00000      +/-  0.0          
   7    1   borus02    z                   0.0          frozen
   8    1   borus02    norm                1.00000      +/-  0.0          
________________________________________________________________________


Fit statistic  : Chi-Squared              1.338520e+07     using 46 bins.

Test statistic : Chi-Squared              1.338520e+07     using 46 bins.
 Null hypothesis probability of 0.000000e+00 with 39 degrees of freedom
 Current data and model not fit yet.
```

Example file is https://sites.astro.caltech.edu/~mislavb/download/borus02_v170323/borus02_v170323a.fits

So you can see the redshift range is 0 to 5, as we use. So how do we allow the parameter to be changed?

```
In [1]: from sherpa.astro.ui import *
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find ds9 on your PATH'

In [2]: load_xstable_model("joe", "../data/borus02_v170323a.fits")

In [3]: type(joe.ecut)
Out[3]: sherpa.astro.xspec.XSBaseParameter

In [4]: type(joe.z)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 type(joe.z)

File ~/sherpa/sherpa-main/sherpa/models/model.py:591, in Model.__getattr__(self, name)
    588         warn(lowered_name, parameter.name)
    589     return parameter
--> 591 NoNewAttributesAfterInit.__getattribute__(self, name)

AttributeError: 'XSTableModel' object has no attribute 'z'

In [5]: type(joe.redshift)
Out[5]: sherpa.astro.xspec.XSBaseParameter

In [6]: type(joe.norm)
Out[6]: sherpa.models.parameter.Parameter
```

Since it's `XSBaseParameter` we can not use `joe.redshift.set(hard_max=10)` which we could do if it were `XSParameter`. 

I have seen crashing code because of users setting parameters outside the set limits of table models, wihch is why we use `XSBaseParameter` for them, but it's less clear with the redshift parameter, so I think just changnig that to `XSParameter` and then requring a user to set the hard_max outside the limit (which is a hint that all bets are off) is okay here.
