### ISSUE TITLE
wstat with zero background

### ISSUE THREAD

**Issue by sfzastro** [sherpa/sherpa#1860]
Hi,

If the background has zero count in a bin, the background model should be zero as well (though unphysical and not recommended), and wstat falls back to c-stat.

Two cases are considered if the background is zero in sherpa/include/sherpa/stats.hh
```cpp
} else if ( 0 == bkg_raw[ ii ] ) {

        if ( msubi < src_raw[ ii ] / src_bkg_time )
          fvec[ ii ] = - tb_msubi - src_raw[ ii ] * ln_ts_div_src_bkg_time;
        else {
          DataType log_src_model = 
            src_model[ ii ] <= 0 ? trunc_value : std::log( src_model[ ii ] );
          fvec[ ii ] = src_model[ ii ] + 
            src_raw[ ii ] * ( std::log( src_raw[ ii ] ) - log_src_model - 1 );
        }
```

The second case represents the c-stat, but I do not see a meaning for the first case. I think the first case should be removed.

```cpp
} else if ( 0 == bkg_raw[ ii ] ) {

        DataType log_src_model = 
          src_model[ ii ] <= 0 ? trunc_value : std::log( src_model[ ii ] );
        fvec[ ii ] = src_model[ ii ] + 
          src_raw[ ii ] * ( std::log( src_raw[ ii ] ) - log_src_model - 1 );
```

**Comment by DougBurke** [comment]
For background (which you may know), we implemented the XSPEC CSTAT statistic in two forms

- cstat, where the background is ignored or you give an explicit model
- wstat, where we try to automatically model the background as essentially a bunch of constants (which is unfortunately not magic and has it's own biases - e.g. https://giacomov.github.io/Bias-in-profile-poisson-likelihood/ )

It will take me some time to look at this (as I'm busy with other Sherpa stuff) unless you can tell me that you are seeing something odd or wrong because of it.

**Comment by neobar** [comment]
Thanks. I have tested the codes above utilizing the notebook of Giacomo Vianello. The bias becomes larger if the 1st case is removed. All these can be avoided if the background spectrum is binned.

You can close this issue now.

**Comment by sfzastro** [comment]
Thanks. I have tested the codes above utilizing the notebook of Giacomo Vianello. The bias becomes larger if the 1st case is removed. All these can be avoided if the background spectrum is binned.

I will close this issue.
