### ISSUE TITLE
Do we have to make all backends support all "rich visualization" option?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1905]
With just matplotlib the "rich visualization" support is "whatever matplotlib suppprts". With new backends, such as bokeh #1899, we can now ask "do we have to do exactly the same as the matplotlib version" or can we differ ? Obviously there's

- differences to how a plot is displayed
- but we can also add extra functionality, or add new plot types, or not display certain plot types

I think we should not make the "rich visualization" support a straight jacket and we should allow the different backends to handle things differently (hopefully most of it is automatic, via the plot objects, but it's not always).

This is a spin off from some discussion items and  questions @hamogu has made during developing #1899

**Comment by hamogu** [comment]
I absolutely believe we can differ. We can also have different plot types, so matplotlib support is pretty complete at this point.
In fact, in development and testting I've done things like:
```
d = DataPHAPlot()
d.prepare(...)
with TemporaryPlottingBackend('BokehBackend'):
    d. # to get the rich visualization with a specific backend
```
It works a little. When it works, it works, but there are some kinks where the prepare sets or does not set stuff that a backend code looks for. I have not gotten to the bottom of that - partically because it's a moving target as I continue to edit the bokeh code.

**Comment by DougBurke** [comment]
Yes, this is very-much an issue I wrote with the idea of us quickly coming to the conclusion "we can do different things" and we can all move on with our lives (and have something to refer to at some point in the future).

I think we can close this now then?
