### ISSUE TITLE
superscripts in bokeh axis labels display as "$^2$

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#1937]
This is with the 4.16.0 release, where `plot_source` and `plot_source_component` created a y-axis label (for X-ray data) labelled as

    f(E) Photons/sec/cm$^2$/keV

That is, it contains the latex/matplotlib code for creating a superscript.

![bokeh](https://github.com/sherpa/sherpa/assets/224638/d8a44039-df0e-463d-a7d3-ea1f465e1aca)

Unlikely to be relevant, but this is with bokeh 3.3.2

**Comment by DougBurke** [comment]
I've also seen an issue with an X-axis label (from one of the flux routines), but that's not surprising.

**Comment by hamogu** [comment]
A limitation of the current version of bokeh is that the $ can only appear in the beginning and the end of a string, not in the middle (https://docs.bokeh.org/en/latest/docs/user_guide/styling/mathtext.html#latex). For most labels, I've edited the labels to use math notation all the way through and then mark the non-math text: `$$\mathrm{f(E) Photons/sec/cm}^2\mathrm{/keV}$$`

Bokeh plans to generalize that; it might be fixed in the next release with no effort on our side.
