### ISSUE TITLE
Improving build configuration (e.g. .travis.yml)

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#199]
I think that our current `.travis.yml` file could be improved since
- it is hard for me to identify what is going on in a particular build (there's always going to be some configuration complexity somewhere, but hopefully the current situation can be improved)
- I think it would be better if all the conda packages were installed with one call, to ensure that everything is compatible (the case I've seen involved changes to the NumPy ABI and switching between packages that were built against different versions of NumPy caused build failures).
- it is not clear to me how easy it is going to be to extend to support multiple python versions (maybe I'm missing something obvious in this one!)

Switching to using  [tox](https://tox.readthedocs.org/en/latest/) is one possibility, but I'm sure there are other ways to do this. If anyone has any ideas, please holler.

**Comment by olaurino** [comment]
The real advantage of tox is that it allows to run test builds both locally and on travis, at least to some extent.

I agree that the packages should be installed with a single call, we can do that.

Commit 4e172a7 adds a python 3 build that is allowed to fail. The commit is part of branch `python3`, which in turns builds on the changes introduced in #169.

**Comment by olaurino** [comment]
As we heavily rely on conda to quickly and reliably install dependencies, we should make conda and tox work together.

This recent SO question does not seem promising in this sense:
http://stackoverflow.com/questions/30555943/is-it-possible-to-use-tox-with-conda-based-python-installations

Giving up conda would make things harder or more time-consuming or less reliable (think about compiling and installing numpy, or xspec). Travis has special commands for retrying operations since tools like pip and analogous non-python installers seem to often fail on travis.

We might probably rely on Travis' cache to compensate, but that might end up complicating the configuration rather than simplifying it. Also, we cannot use the cache for xspec builds as they have to run on the GCE infrastructure because we need sudo for installing xspec's special dependencies, plus we were having system issues on travis' linux containers, with the builds often being killed and restarted.

While I think tox is valuable for pure python projects with simple dependency, it might end up being counterproductive for Sherpa.

If there are any suggestions on how to streamline the current travis configuration I'll be happy to find solutions in this sense (and as I mentioned, we can indeed install all the conda dependencies on the same line).
