### ISSUE TITLE
Pytest warning: PytestUnknownMarkWarning: Unknown pytest.mark.xdist_group`

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#2044]
Discovered in 4.16.1 testing on a local source checkout:
```Python
sherpa/utils/testing.py:187
  /Users/guenther/code/sherpa/sherpa/utils/testing.py:187: PytestUnknownMarkWarning: Unknown pytest.mark.xdist_group - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    grp = pytest.mark.xdist_group("ds9-tests")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
with `platform darwin -- Python 3.11.9, pytest-8.2.1, pluggy-1.5.0`.

**Comment by DougBurke** [comment]
This is entirely expected, and was introduced in #1969. We use the `pytest-xdist` feature to allow tests to be grouped together so the DS9 tests can be run sequentially (as otherwise it just borks the tests). Unfortunately this uses the "xdist_group" mark, which you only know about if you have `pytest-dist` installed. It would be nice if we could not get this warning without maknig `pytest-xdist` a required package for testing Sherpa, but I have not spent much time on trying to address this: it appears to be an issue with how `pytest` wants to handle "marks" and I have no interest/desire/time to worry about it.
