### ISSUE TITLE
Sherpa test errors

### ISSUE THREAD

**Issue by cdeil** [sherpa/sherpa#230]
After some time of doing other things, I'm now coming back to Sherpa analyses with Gammapy.

Using the latest `sherpa` master I now get on my Macbook this error:

```
>   from . import numpytest
E   ImportError: cannot import name numpytest

/Users/deil/code/sherpa/sherpa/utils/__init__.py:36: ImportError
```

See full log: https://gist.github.com/cdeil/67947652e06ebe358b0494060c04dc45#file-gistfile1-txt-L126

---

I think my Sherpa install is broken though.

The full install log is here:
https://gist.github.com/cdeil/a6d07ebbd5c88e7c43820f996ee99123

This is the error I get when I try to run the tests via `python2 setup.py test`:
https://gist.github.com/cdeil/a6d07ebbd5c88e7c43820f996ee99123#file-gistfile1-txt-L4361

This is the error when I try to run the tests via `sherpa_test`:
https://gist.github.com/cdeil/a6d07ebbd5c88e7c43820f996ee99123#file-gistfile1-txt-L4407

Am I doing something wrong or are these bugs in the Sherpa install / test code?

**Comment by olaurino** [comment]
It looks like the same error reported in issue #198. In that case we never figured out what the cause was, but a new build in a new conda environment was successful. One reason we stopped investigating the issue was that there were some strange issues with the main conda environment, i.e. `pip` was being picked up from different, unexpected locations.

I could never reproduce the issue. I remember experiencing it once several weeks ago and I found out I had two different sherpa instances, one installed through `python setup.py install` and one with `python setup.py develop`. Cleaning up with `pip uninstall sherpa` run as many times as required to remove all of the instances, then running `git clean dfx`, and a new `python setup.py develop` fixed the issue for me, but then when I tried reproducing it I just couldn't, no matter how hard I tried.

A wild guess is that something is wrong with importing `absolute_import`. Either I made a mistake in importing it, or somehow Python does not update some of the `.pyc` files, but that wouldn't explain why the user reporting #198 could not fix the build in her main environment after cleaning up everything we could think of, unless her issue is unrelated.

Could you please report the commit your master branch was at before the latest update?

**Comment by cdeil** [comment]
This issue is from 2016 and I don't remember having seen the issue since. Closing.
