### ISSUE TITLE
backscal column not treated properly for WStat

### ISSUE THREAD

**Issue by joleroi** [sherpa/sherpa#248]
If you provide the background scaling factor not as a header keyword but as data column the implementation of wstat cannot deal with this:

```
import sherpa.astro.ui as sau
import numpy as np

sau.load_pha('/home/kingj/Software/sherpa/sherpa-test-data/sherpatest/3c273.pi')
sau.ungroup()
source_backscal = sau.get_data().get_backscal()
bkg_backscal = sau.get_bkg().get_backscal()
n_channels = len(sau.get_data().channel)

sau.get_data().backscal = np.ones(n_channels) * source_backscal
sau.get_bkg().backscal = np.ones(n_channels) * bkg_backscal

sau.set_stat('wstat')

sau.set_model('bbody.source')
sau.notice(2,20)
sau.fit()
```

raises this error

```
Traceback (most recent call last):
  File "analyse.py", line 17, in <module>
    sau.fit()
  File "<string>", line 1, in fit
  File "/home/kingj/Software/sherpa/sherpa/astro/ui/utils.py", line 9262, in fit
    self._fit(id, *otherids, **kwargs)
  File "/home/kingj/Software/sherpa/sherpa/astro/ui/utils.py", line 9366, in _fit
    res = f.fit(**kwargs)
  File "/home/kingj/Software/sherpa/sherpa/fit.py", line 58, in run
    result = func(fit, *args, **kwargs)
  File "/home/kingj/Software/sherpa/sherpa/fit.py", line 1107, in fit
    init_stat = self.calc_stat()
  File "/home/kingj/Software/sherpa/sherpa/fit.py", line 1021, in calc_stat
    bkg=bkg_data)[0]
  File "/home/kingj/Software/sherpa/sherpa/stats/__init__.py", line 601, in calc_stat
    truncation_value)
TypeError: statistic input array sizes do not match
```

The problem is that the information about noticed channels is not forwarded to the backscal array, uncommenting the sau.notice() line 'solves' the error, uncommenting the sau.ungroup() line introduces it again

```
(Pdb) bkg_data['data_size']
array([888])
(Pdb) len(bkg_data['backscale_ratio'])
1024
```

I would be happy to try fixing this myself and am thus grateful for any hint where to start.

**Comment by DougBurke** [comment]
We have the long-overdue PR #195 which hopefully makes the API for passing around the background information a bit clearer. My guess would be that it's somewhere in `get_bkg_args` (or `get_extra_args` in the PR), or somewhere similar, but I do not have a strong grasp of this part of the code base.

**Comment by DougBurke** [comment]
I seem to have a fix for this in PR #269 - but it needs some discussion as

- it is late

- it needs to be integrated (in particular #195 - which I don't expect to be hard)

- should the background data being sent around to wstat (and anything else that wants it) be forced to use the same grouping for the background and source data set (this is likely implied by the existing code, in particular the calculation of the backscale ratio, but perhaps the two components could be separated and the division done by the statistic). I am too tired to know if this even makes sense

**Comment by joleroi** [comment]
Indeed, the example script above runs fine using #269.

Also my private analysis script give correct results using #269 

Thanks @DougBurke !

**Comment by DougBurke** [comment]
I can't guarantee it will be pulled into master immediately. We are trying to get a 4.8.2 release out of the door (focussing on the python 3 work) and this change is potentially invasive as it's a part of the system we haven't had good tests for (as we've found out in this PR ;-), as well as the fact I am not too happy with the code itself (but I think that my refactoring plan https://github.com/sherpa/sherpa/pull/269#issuecomment-245900117 might help that, but that needs review and thought by people other than myself)!

**Comment by DougBurke** [comment]
# Current status

PR #269 looks to fix this problem (e.g. the tests marked as `xfail` in PR #267 now pass), but I am not a fan of this approach as it hard-codes some logic in `sherpa.fit.Fit`, namely that the source and background data is to be filtered and grouped using the same scheme. At the moment `sherpa.stats.WStat` is the only statistic to take advantage of this functionality (excluding some of the test code), so it does not break anything, but it is not particularly extensible.

# In development

I am working on code which moves the logic from `sherpa.fit.Fit` and places it into `sherpa.stats.Stat` (and which can be extended or overloaded by sub-classes). At present the only code that is checked in is the test suite I am developing to test this out, but I wanted to note down some of the thoughts behind it here, for review and comment.

## Current implementation

The `sherpa.fit.Fit` class contains code that extracts the data arrays (independent and dependent axes, along with any statistical and systematic errors) and sends them to the stats object, which calculates the statisitic of this model, using the `sherpa.stats.Stat.calc_stat` routine. The API of this routine is

     def calc_stat(self, data, model, staterror, *args, **kwargs):
        raise NotImplementedError

and the parameters - e.g. `data`, `model` are expected to be one-dimensional NumPy arrays (or something that can be cast to a 1D array for the C API). The actual calculation of the statistic is done by the C code in `sherpa/include/sherpa/stats*.hh` (it's a bit of a maze here), as the following is one of the implementations of this method:

    @staticmethod
    def calc_stat(data, model, staterror, *args, **kwargs):
        syserror, weight, extra = get_syserror_weight_extra(kwargs)
        return _statfcts.calc_chi2_stat(data, model, staterror,
                                        syserror, weight, truncation_value)

The `sherpa.fit.Fit` class is sent in `sherpa.data.Data` and `sherpa.models.model.Model` objects (or the `*SimulFit*` variants) and so has to extract the numeric arrays from these objects to send to the `calc_stat` method of the statistic. This happens in several places, and for now I am concerned with the `sherpa.fit.Fit.calc_stat` routine (although, as noted below in the Issues section, it will have to apply in other places too), which relies on `sherpa.fit.IterFit.get_extra_args`, since why would one class be used when it can be spread over two classes!

## Proposed implementation

One major problem with having the code to extract the numeric arrays from the data/model objects in the fit object is that it is not very extensible. This is actually one of my concerns with the fix in PR #269, since it assumes that any statistic that needs this information is going to want the "extra data" it provides (such as the BACKSCAL ratio), and forces the source and background data to be binned and grouped the same way. 

An improvement is to move the "extraction" logic - that is, the code that takes the Data and Model objects and gets the numeric arrays for the axes, along with any ancillary information - into the statistic itself. So, change `sherpa.stats.Stat.calc_stat` from

     def calc_stat(self, data, model, staterror, *args, **kwargs):
        "The parameters are arrays"
       ...

to

     def calc_stat(self, data, model, *args, **kwargs):
        "The data and model arguments are sherpa.data.Data/sherpa.models.model.Model instances"
       ...

and then `calc_stat` can extract the information it wants. The reason for removing `staterror` is that this is not needed in all cases (e.g. our likelihood stats) and so does not make sense to be in the base class. With these changes, the C++ API (e.g. `sherpa/include/sherpa/stats*hh`) can be changed so that the functions are more-closely related to the data (e.g. likelihood routines do not need to be sent stat/syserror arrays).

As an implementation detail I'm actually writing a new method, `calc_stat_from_data`, which uses the new form of the API, but leaves the old code present for testing.

## Issues

I have been concentrating on `sherpa.fit.Fit.calc_stat` and `sherpa.stats.Stat.calc_stat` but there are other methods in `sherpa.fit.Fit` and `sherpa.stats.Stat` that will need an update. The intention is to add tests for these methods and then do the conversion.

There is a question over how much use of the `DataSimulFit` and `SimulFitModel` classes should be assumed versus support for both the single and simultaneous versions, but I think that's an implementatino detail to worry about later.

It is a breaking update to the sherpa API. We don't have an established policy of what to do here, and this is a lower-level API (i.e. it should not affect users of `sherpa.astro.ui`/`sherpa.ui`), which might mean it's "easier" for us to change things, but I wanted to call this change out.

I wonder if there is a use for having a method on the `sherpa.stats.Stat` object that makes it easy to calculate the statistics given 2 or more arrays (e.g. following the current API). This would be for users who only want to use a small part of Sherpa (maybe just the `sherpa.stats` module) since they have other code for the other parts. I am sympathetic to this, but feel that we should just make it easier for users to use the Data1D/... classes (i.e. improve the documentation) and take advantage of this functionality.

**Comment by joleroi** [comment]
I am not familiar enough with the Sherpa code base to give useful feedback here, but what you propose seems reasonable. Let me know if you need me to test something.

**Comment by DougBurke** [comment]
I've just made a WIP commit of my proposed rewrite, see PR #287.
