### ISSUE TITLE
Test fails on Python 3

### ISSUE THREAD

**Issue by cdeil** [sherpa/sherpa#260]
Sorry if I've brought this up before!
If so, please close and point me to the answer.

I have Sherpa master installed, with Python 3.5 from Macports and latest stable Setuptools, Numpy, Astropy, Pytest 2.9.

From the git repo:

```
$ python setup.py test
...
    [Errno 13] Permission denied: '/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/test-easy-install-31449.write-test'
```

Full output: https://gist.github.com/cdeil/7bc2fc9301bb8b0e2bf335ff31e6981d

From another folder

```
$ sherpa_test
```

gives a ton of test errors from plotting tests because I don't have the test data:
https://gist.github.com/cdeil/5cf3919209ea1c7913108461170a406c

Here's the first:

```
_______________________________________________________ ERROR at setup of test_plot[model-args0] _______________________________________________________

ui = <module 'sherpa.astro.ui' from '/Users/deil/Library/Python/3.5/lib/python/site-packages/sherpa/astro/ui/__init__.py'>
make_data_path = <function make_data_path.<locals>.wrapped at 0x10b8a3378>

    @requires_fits
    @pytest.fixture(autouse=True)
    def load_data(ui, make_data_path):
        """
        Load dataset before every test.
        """
>       ui.load_data(make_data_path("3c273.pi"))

/Users/deil/Library/Python/3.5/lib/python/site-packages/sherpa/astro/ui/tests/test_chips_unit.py:66: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Users/deil/Library/Python/3.5/lib/python/site-packages/sherpa/conftest.py:140: in wrapped
    return os.path.join(path, arg)
/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/posixpath.py:89: in join
    genericpath._check_arg_types('join', a, *p)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

funcname = 'join', args = (None, '3c273.pi'), hasstr = False, hasbytes = False, s = None

    def _check_arg_types(funcname, *args):
        hasstr = hasbytes = False
        for s in args:
            if isinstance(s, str):
                hasstr = True
            elif isinstance(s, bytes):
                hasbytes = True
            else:
                raise TypeError('%s() argument must be str or bytes, not %r' %
>                               (funcname, s.__class__.__name__)) from None
E               TypeError: join() argument must be str or bytes, not 'NoneType'

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/genericpath.py:143: TypeError
```

@joleroi - I think you're seeing the same plotting test fails on Python 3 with Anaconda on Linux?

**Comment by olaurino** [comment]
Hmm... hopefully adding `@requires_data` to the `load_data` fixture will fix the tests issue.

we probably need a travis build with no optional dependencies at all, so we can catch this kind of issues and test a fix. I was sure we had one :confused:

The first `permission denied` error is more obscure. At first glance, it looks like a local issue: for some reason `develop` thinks it has to install in a system folder, which should not be the case. I'll see if I can reproduce the issue on my mac.

**Comment by olaurino** [comment]
I can reproduce the permission denied issue. It's surprising, because `develop` should not care about writing access in the system folders. On the other hand, we always test with `conda`, so there may be issues I have overlooked when using OSX's system python rather than conda. I'll need to look more into this, and I'll try and reproduce the issue on Linux or with Python 2.7 on OSX.

**Comment by olaurino** [comment]
@cdeil, I may have misunderstood your report. If that's true, I am sorry.

It actually makes sense that `develop` needs to write at least once into the system folder for registering the package, even if just as a link. I am so used to using virtualenvs and conda that I forgot.

But rereading your report you said:

> I have Sherpa master installed,

I guess you mean that you ran `sudo python setup.py install` or you installed sherpa in a user folder or a virtual environment, right? In this case you should not use `test`, unless you change the alias in `setup.cfg`, and even in that case you probably need to tweak the pytest arguments to point pytest to the installed modules rather than the current folder.

`test` is tweaked to be used during development, and it calls `develop`. `sherpa_test` should be used otherwise.

I now remember that you did ask this, I just didn't understand the issue :) And after you asked we added the following section to our README:
https://github.com/sherpa/sherpa/blob/master/README.md#2e-development-mode

Does this make sense? If so, then this issue just has to do with being able to skip or run the plot tests when no data files are available, either by marking `load_data` with the `@requires_data` decorator, or by loading data without having to rely on disk I/O and the test data folder. And we need a Travis build with no optional dependencies.

**Comment by cdeil** [comment]
Ah, sorry, I wasn't very clear and didn't realise `test` runs `develop` and needs write access to site-packages.

This is not how `python setup.py test` is implemented in Astropy (probably astropy-helpers).
There it only touches files in the local folder and (I think) copies a version over to `/tmp` and runs it there.

This is the behaviour I was expecting, so I thought `python setup.py test` in Sherpa trying to write to `site-packages` is a bug and filed this issue.

I've never installed Sherpa with sudo, I used this:
```
python setup.py install --user
```
which for me goes to
```
/Users/deil/Library/Python/3.5/lib/python/site-packages/sherpa
```

So if I want to leave that installation (and system=Macports Python) site-packages alone,
and just try out Sherpa dev or code on Sherpa dev without installing it, how should I run the tests?
Do I need to make a virtual or conda env?

**Comment by olaurino** [comment]
You can use `sherpa_test`.

**Comment by cdeil** [comment]
Well, `sherpa_test` from the source directory doesn't work:
https://gist.github.com/cdeil/a1313532479e6cd1a470ae623a98e291

`python setup.py build_ext -i` is not mentioned on
https://github.com/sherpa/sherpa/blob/master/README.md

So I still find it confusing and none of the ways described in the README to test in development mode (which for me means not touching `site-packages` where my production install is) works:

https://github.com/sherpa/sherpa/blob/master/README.md#2d-testing-the-build
https://github.com/sherpa/sherpa/blob/master/README.md#2e-development-mode
https://github.com/sherpa/sherpa/blob/master/README.md#3b-built-from-source

I guess I should make a virtualenv, then `python setup.py test` would just work, right?

**Comment by olaurino** [comment]
> I guess I should make a virtualenv, then python setup.py test would just work, right?

Yes. So it would in a conda environment.
Also, `build_ext` is not mentioned because it's included in the aliases defined in `setup.cfg`, that you are free to modify.

Probably it's because it's Friday afternoon, but I still don't think I understand why you are saying the instructions in the README do not work. I apologize for that.

You are saying that you have a production version of `sherpa` installed, right?

Now I am not sure I understand what you are trying to do next: do you want to run the sherpa tests for a different sherpa version/commit built from the source repo without affecting you production installation and without running `develop` or `install`? In that case you are right and our README instructions do not cover this case. They assume you install sherpa somewhere, using `develop` or `install`.

I haven't tested this option, but in your case you can probably just run `python setup.py build_ext --inplace` and then `py.test .` That should do it. You could also modify `setup.cfg` and replace the `test` alias with `build_ext --inplace test`. And you could instruct `git` to ignore the change (`git update-index --assume-unchanged setup.cfg`).

Unfortunately Python lacks standardized project management tools like `maven` for Java, so all projects have slightly (or less slightly) different ways of managing the development lifecycle. For sherpa, we chose to set things so that they work out of the box in the most common scenarios, and we devoted `python setup.py test` to serve developers and `sherpa_test` to serve users installing sherpa with conda binaries or via `install`.

I never thought of the case where one might want to run the tests without running either `install` or `develop`.

Note that for sherpa we also have the `sherpa_config` and `xspec_config` commands, so users and developers need a way to run the correct pipeline in order to have a correct build, which is why `build_ext`, `develop`, and `test` are aliased. And in CIAO the default configuration is heavily modified.

Does that make sense or I still don't get it? If that's the case I guess I'll have to use the long weekend (Monday is a holiday in the US) to recharge the batteries and hopefully I'll be more receptive on Tuesday :)

**Comment by cdeil** [comment]
> do you want to run the sherpa tests for a different sherpa version/commit built from the source repo without affecting you production installation and without running develop or install?

Yes, that's how I usually code on Python projects (Astropy, Gammapy, ...).
I get the git repo and run `python setup.py test` or `py.test` there and never touch `site-packages` or make a `venv` or conda env.

This mostly works for me:
```
F90=gfortran-mp-5 python setup.py build_ext -i
py.test -v
```
except for these two fails!?
https://gist.github.com/cdeil/33513ae2d6936ba920996b83c68687c8#file-gistfile1-txt-L446

(I did run `git submodule update` to be sure I have the latest version of the test files just now.)

I'm not sure it's necessary to make additions or changes to your install / dev / test description in README. It's very extensive, thank you!

Maybe these comments would have helped me understand what's going on and possibly could be useful:
- `python setup.py test` will run `python setup.py develop` which will touch files in `site-packages`.
- If you don't want to touch your `site-packages` while hacking on sherpa, either make a new venv or conda env, or run `python setup.py build_ext --inplace && py.test`.

**Comment by olaurino** [comment]
> except for these two fails!?
> https://gist.github.com/cdeil/33513ae2d6936ba920996b83c68687c8#file-gistfile1-txt-L446

Hmm... that's new. Never saw those tests fail or that error message for that matter. I'll see if I can reproduce the issue, but it will have to wait until next week.

Thanks for your patience and have a good weekend.

**Comment by DougBurke** [comment]
@cdeil - a bit of a long shot but I'm wondering if this is related to either

- #50 and/or #131 
- #232 

I can't quite see how they could be related to the errors you see, but you never know.

Do the following commands work for you?

```
In [1]: from sherpa.astro import ui

In [2]: from sherpa.astro.utils import _wcs

In [3]: 
```

If it's not this, what version of `astropy` are you using?

**Comment by cdeil** [comment]
@DougBurke I'm getting this:
```
In [1]: from sherpa.astro import ui
WARNING: imaging routines will not be available, 
failed to import sherpa.image.ds9_backend due to 
'RuntimeErr: DS9Win unusable: Could not find xpaget on your PATH'
WARNING: failed to import WCS module; WCS routines will not be available
WARNING: failed to import sherpa.astro.xspec; XSPEC models will not be available

In [2]: from sherpa.astro.utils import _wcs
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-a18e207253dd> in <module>()
----> 1 from sherpa.astro.utils import _wcs

ImportError: dlopen(/Users/deil/Library/Python/3.5/lib/python/site-packages/sherpa/astro/utils/_wcs.cpython-35m-darwin.so, 2): Symbol not found: _pix2wcs
  Referenced from: /Users/deil/Library/Python/3.5/lib/python/site-packages/sherpa/astro/utils/_wcs.cpython-35m-darwin.so
  Expected in: flat namespace
 in /Users/deil/Library/Python/3.5/lib/python/site-packages/sherpa/astro/utils/_wcs.cpython-35m-darwin.so
```
I have the latest stable Astropy 1.2 installed with Macports.

**Comment by DougBurke** [comment]
I'm currently making pancakes for the kids, and am out tomorrow as well, so
I won't be much help for a while. There's a couple of things here which I
can't answer at the moment

- the test should probably have a 'is wcs available' decorator
- why is the _pix2wcs symbol not found in this case

**Comment by DougBurke** [comment]
I've just tried to unravel the build behind the _wcs module and quickly discovered "it's complicated" and have decided to leave it to @olaurino! My assumption here is that there's some problem in building the library (or the external lib it needs), perhaps due to the issue we have seen with ordering of astropy and sherpa installs.

The other issue is what it means for the wcs code to be an optional dependency. Sherpa supports it - as seen in the output shown by @cdeil above - but do we want to skip tests when the WCS fails to build or still error out? It may be that we should skip the tests since wcs isn't available, but then how do we idenitfy cases of "wcs not built on purpose" versus a situation like this where it has failed to build.

To go with this, it's not clear to me *how* to tell not to build the _wcs module (i.e. it doesn't seem to act like the region or stack libraries/components).

**Comment by olaurino** [comment]
I can reproduce the error on my laptop. I'll get back to it later as I can't debug it right now. However, the relevant `wcs` routines are shipped with sherpa and built with it, so I am not sure I see this as a "missing dependency" issue. What might be happening (it's just a suspicion) is that since @cdeil is not installing sherpa in an environment via `develop` or `install`, libraries are being picked up incorrectly from somewhere in the system. Sherpa relies on some external libraries (`region`, `wcssubs`, `fftw3`) to be installed. You can point Sherpa to local versions of these libraries in the `setup.cfg` file, otherwise they are built and installed together with Sherpa. My suspicion is that if you don't run one of `develop` and `install` something gets linked wrong, or libraries are resolved incorrectly.

I'll have more info when I can actually debug it.

**Comment by DougBurke** [comment]
Is this a Python 3 issue or is the python version irrelevant, @olaurino ?

**Comment by DougBurke** [comment]
I'm just trying the `python setup.py build_ext -i; py.test -v` approach with the current `master` (so Sherpa 4.9.0 +  #335 and a few others) and note that I manually have to install `six` and `mock`. Is this expected, or do we need to try and improve the build here (as we did in #335)? I'm guessing the current behavior is okay (since we don't have a place to specify that mock is needed when running `py.test`).

**Comment by DougBurke** [comment]
If you run the tests you see that those that require the `stk` and `group` module are being skipped (well, once #336 is applied they are). This means that those modules are either not getting built, or being built incorrectly, with the `build_ext` approach.

**Comment by olaurino** [comment]
@DougBurke what is the use case for using `build_ext` only? This is one part of the build pipeline, but there is much more to it, so I am not surprised there are issues. I sometimes use `build_ext` directly when I need to force a build of the extension *after* I have created a full build (usually with `develop`. The stack and group modules are not Sherpa extensions, they are built from the `extern` folder and installed into the environment as part of Sherpa's `install`-like phases. In other terms, `stk` and `group` are not supposed to be built and installed as part of the `build_ext` command. We could move things around, but I don't really think there is a compelling reason for doing it.

**Comment by DougBurke** [comment]
My use case is just that @cdeil says he uses this approach to build python packages. I think it's fine if we don't feel there's a strong use case to support this approach, but it's worth being explicit about that choice (I don't mean we need to add it to the README, but it would be something we would have in our developer docs, once they are written).

Does this mean we can close this issue now, or is there still work needed to be done?

**Comment by olaurino** [comment]
I would say it's up to you and @cdeil. My inclination is that we did a lot of work to make something as complex as Sherpa build easily in 90% of the cases (the number is arbitrary). The case where you don't use `install` or `develop` seems unsafe because you have to hope dependencies are matched correctly, as opposed to having virtual envs or conda environments and using `install` or `develop`.

But then again, we could probably make it work given time and a high priority.

**Comment by DougBurke** [comment]
I personally don't see it as a priority, but then again I don't use `build_ext` :-)

**Comment by cdeil** [comment]
Today with Sherpa master I did `python setup.py develop` and then both `python setup.py test` and `pytest -v` work fine for me.

I think the issue reported here is either resolved, or was a usage error on my side, I don't know.
Closing.

@olaurino  and @DougBurke - Thank you for all your work on Sherpa and help with such setup questions!
