### ISSUE TITLE
save in python3

### ISSUE THREAD

**Issue by kglotfelty** [sherpa/sherpa#297]
Reposting here:

There is a problem with the `save` command in python3 -- it throws a NameError exception.

```python
% python
Python 3.5.1 (default, Apr  6 2016, 12:14:18)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sherpa.astro.ui import *
>>> load_data("out.pi")
read ARF file out.arf
read RMF file out.rmf
>>> save("savit", clobber=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1, in save
  File "/export/ciaox_install/20161026P3/ciao-4.9/lib/python3.5/site-packages/sherpa/astro/ui/utils.py", line 230, in save
    sherpa.ui.utils.Session.save(self, filename, clobber)
  File "/export/ciaox_install/20161026P3/ciao-4.9/lib/python3.5/site-packages/sherpa/ui/utils.py", line 470, in save
    fout = file(filename, 'wb')
NameError: name 'file' is not defined
>>> _sherpa_version
'4.8.1+133.ge819bd1'
```

I don't think it's specific to the particular input file I'm using.  The same works in python 2.7.

**Comment by wmclaugh** [comment]
Hi Kenny-

Thanks for the report. The issue is not the input file that you are using
but is actually a python 3 compatibility issue. The code used for the save
and restore functionality is using the file builtin- ie.  file('filename').
This works in python 2 but needs to be updated for python 3. Changing the
routines to use  open('filename') will allow the same code to be used for
python 2 or 3.

-Warren
