### ISSUE TITLE
Creating a Debian/Ubuntu package

### ISSUE THREAD

**Issue by olebole** [sherpa/sherpa#3]
Hi,

I just read about sherpa on the [astrostatistics facebook timeline](https://www.facebook.com/groups/astro.r/permalink/802994106463263/), and I wonder if you would like to create Debian/Ubuntu package?

Ideally, this should be done within the [Debian Astronomy working group ](https://lists.debian.org/debian-astro/). You could do it yourself, or anyone else can volunteer. As far as I could see, the package is quite standard, so the packaging should be not too difficult.

Please contact me directly, or via the  [mailing list](mailto:debian-astro@lists.debian.org) list if you need further information. We can guide you through the full process, and also finally upload your package to Debian. Once it is in Debian, it will automatically migrate to distributions like Ubuntu or Mint.

Best regards

Ole

**Comment by olaurino** [comment]
Hi Ole,

we are definitely interested in understanding the process and having Sherpa in Debian. I'll contact you so that we can get more info.

Thanks,

Omar.

**Comment by cdeil** [comment]
ITP = intent to package filed:
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=795370

**Comment by olaurino** [comment]
Thanks @cdeil, this is great news. Could you please document the process in a shared place (maybe we can use the GitHub Wiki?). Please let me know if you need any support.

**Comment by cdeil** [comment]
I thought I'll just use this issue to make progress update comments and leave notes and ask questions.

Then at the end, I can summarise important info on a GH wiki page, including step-by-step instructions how to get the Debian package updated after a new Sherpa version.

@olaurino – Does this sound OK?

**Comment by olaurino** [comment]
@cdeil it sounds OK. Of course, the more you can document the better. :)

**Comment by cdeil** [comment]
I just wanted to say that yesterday @olebole walked me through most of the steps to create a package (see [here](https://wiki.debian.org/DebianAstro/AstropyPackagingTutorial/Packaging)) using Gammapy as an example. I'm on holiday for a week now, and when I get back I'll start with Sherpa.

One thing I didn't know before: most of the work is to go through every single file and check that the license / copyright is OK. E.g. scikit-image is currently under threat from being removed from Debian because they included a single non-free example image file (see [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794859)). Common issues are bundled or copied code from non-free sources, especially from Numerical recipes.
So @olaurino, if you or someone from the Sherpa team has the time to do this check, that is really the bulk of the work, and the rest is mostly mechanical and not so much work (unless there are build / install issues).

For now it's clear that Sherpa is GPL3+, but as we've discussed before, it would be great if it could be licensed more liberally, e.g. as BSD-3 like Numpy / Scipy / Astropy / ..., so that Sherpa could be used more widely as part of the scientific Python stack.
As far as I know (but I might be wrong) the choice of GPL3+ isn't because CXC or the Sherpa devs specifically want that license, but because of the fftw or other dependencies? In this case, @olebole pointed out that Sherpa can still have a more liberal license, and just the combined whole is GPL3+.
I don't want to start a license discussion here, I'm just pointing this out in case you do a thorough license / copyright check, then maybe this could be done in a single go also considering the possibility which files in Sherpa could be more liberally licensed.

**Comment by olebole** [comment]
I would just add the link to an [Blog entry of the yt project](http://blog.yt-project.org/post/Relicensing.html) that deals with the whys and hows of their transition from GPL to BSD.

**Comment by olaurino** [comment]
@cdeil we did the exercise of reviewing the whole Sherpa codebase looking for licensing issues not long ago. The summary of the work is expressed in the contents of this file:
https://github.com/sherpa/sherpa/blob/master/COPYRIGHT

We have internal documentation with more detail, e.g. the location of the code mentioned in the above file. Please let me know if more information is required.

We did our best to ensure there are no violations to the GPL license, and to the best of our knowledge there are no issues. However, since this is a rather complex field, mistakes are always behind the corner (e.g. I did not know that the Lenna picture, for better or worse the most popular image manipulation example, was not free... and an incredible number of packages must have dealt with this issue at some point).

Note that the GPL constraints are more than just linking to fftw, as we embed code with a GPL license: in order to release Sherpa under a less restrictive license we should remove that code or ask the copyright holders to relicense it, although the latter option is rather unlikely.

One of the reasons for our licensing review was also to figure out what we would need to do in order to release Sherpa under a different license, but there seems to be a good deal of work involved for that to happen.

**Comment by olaurino** [comment]
As a reminder to myself, I also have to update the COPYRIGHT year :)

**Comment by olebole** [comment]
I would like to bring this topic up again -- it would be nice to have Sherpa in Debian. [Debian#795370](https://bugs.debian.org/795370) is still open ;-)

If there is any interest in working on it, please contact me/us. We would be glad to help.

**Comment by hamogu** [comment]
This has been open for > 8 years with no progress and while it would still be nice to a have a Debian (and other distros) native package, two things have happened since 2015: Our resources to develop and maintain Sherpa have decreased significantly, and advances in Python packaging have made it easier to install Python packages and dependencies. We provide conda binaries for Sherpa and Sherpa also installs with pip out of the box.
Thus, I'm closing this issue and recommend to also close the associated Debian ticket.

If you disagree strongly, feel free to re-open, preferably with a suggestion who can do the work and maintain the Debian package.
