### ISSUE TITLE
unexpected behavior with masked arrays

### ISSUE THREAD

**Issue by douglase** [sherpa/sherpa#346]
Sherpa version 4.9.0, Python 2.7.12,  NumPy 1.11.2 (also seen on NumPy 1.12.1)
This issue was discovered when fitting a masked 2D array but is easily reproducible with the first few lines of the example notebook:

Create a masked numpy array:
```
x = np.arange(-5, 5.1)
y = x*x + 23.2 + np.random.normal(size=x.size)
old_y = x*x + 23.2 + np.random.normal(size=x.size)
y = np.ma.masked_array(old_y,mask=y<35)
e = np.ones(x.size)

sherpa.load_arrays("mydata", x, y, e)
sherpa.plot_data("mydata")
print(y.mask)

```
The mask appears set but the data points still appear.
If you multiply the masked array by 1.0 (or as I noticed this, by taking the sqrt of an array) the behavior changes:

```
y = 1.0*np.ma.masked_array(old_y,mask=y<35)
sherpa.load_arrays("mydata", x, y, e)
sherpa.plot_data("mydata")
print(y.mask)
```

Screenshots:

<img width="555" alt="screen shot 2017-03-31 at 4 29 50 pm" src="https://cloud.githubusercontent.com/assets/1025951/24568255/4b58c3ba-162f-11e7-8ed7-54ee52b69d96.png">

This still produces unexpected behavior, as these new zero values aren't just plotted, they got included in the fit further down the notebook. 
### Work around
Forcing masked values in y to np.nan gives the expected behavior, e.g.
`y = np.ma.filled(1.0*np.ma.masked_array(old_y,mask=y<35),fill_value=np.nan)` then the masked y data points are neither plotted or fitted.

**Comment by olaurino** [comment]
I don't think Sherpa currently supports numpy masked arrays. As a matter of fact, when trying to reproduce the issue in CIAO `load_arrays` fails because the code in the CIAO backend explicitly checks that the arrays are of certain types. This is not to say such behavior is correct, of course. I'll take a closer look to see if we could easily accommodate numpy masked arrays and keep you posted.

In the meantime, Sherpa offers its own method for setting a filter. The catch is that it follows a different convention by default (a positive value or `True` for a "bad" channel, 0 or `False` for a good channel), so you need to negate the mask or set a special keyword, e.g.:

```` python
from sherpa.astro import ui as sherpa
import numpy as np

x = np.arange(-5, 5.1)
y = x*x + 23.2 + np.random.normal(size=x.size)
old_y = x*x + 23.2 + np.random.normal(size=x.size)
y = np.ma.masked_array(old_y,mask=y<35)
e = np.ones(x.size)

sherpa.load_arrays("mydata", x, y, e)
sherpa.set_filter("mydata", y.mask, ignore=True)
sherpa.plot_data("mydata")
````

This should give you the expected result. See also http://cxc.harvard.edu/sherpa/ahelp/set_filter.html
