### ISSUE TITLE
allow the user to specify multiple back ends in their ~/.sherpa.rc file

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#348]
It would be useful if we could change the backend (plotting or I/O) while running Sherpa (or at least interactively). This is a "power user" feature, and would probably require a lot of work.

A simpler approach (hopefully) would be to allow users to specigy multiple backends in their ~/.sherpa.rc file, with the order listing preference, and then loop through them until one works or none do [I'm allowing for the possibility of there being > 2 backends, even if this is not the case at present].

With this, I could set

```
[options]
plot_pkg   : pylab chips
```

which would prefer the matplotlib backend but allow the use of ChIPS if matplotlib isn't available (or can't be loaded). I assume that a space-separated list is okay here (i.e. we do not need to worry about backend names with a space in them; as we control these names that should be a restriction we can add if necessary).

**Comment by hamogu** [comment]
As a power-user you can do that by directly assigning the module you want to the `sherpa.astro.io.backend`"
```
sherpa In [1]: import sherpa.astro.io

sherpa In [2]: back = sherpa.astro.io.backend

sherpa In [3]: back
Out[3]: <module 'sherpa.astro.io.pyfits_backend' from '/Users/hamogu/anaconda3/envs/ciao/lib/python3.7/site-packages/sherpa/astro/io/pyfits_backend.py'>

sherpa In [4]: import sherpa.astro.io.pyfits_backend

sherpa In [5]: sherpa.astro.io.backend = sherpa.astro.io.pyfits_backend

sherpa In [6]: back = sherpa.astro.io.backend

sherpa In [7]: back
Out[9]: <module 'sherpa.astro.io.pyfits_backend' from '/Users/hamogu/anaconda3/envs/ciao/lib/python3.7/site-packages/sherpa/astro/io/pyfits_backend.py'>

sherpa In [8]: load_pha('code/sherpa/sherpa-test-data/sherpatest/12845.pi')
read ARF file code/sherpa/sherpa-test-data/sherpatest/12845.warf
read RMF file code/sherpa/sherpa-test-data/sherpatest/12845.wrmf
WARNING: file 'code/sherpa/sherpa-test-data/sherpatest/12845_bkg.pi' not found
```
I don't think we need an UI-level function to change the backend for astro.io, this is kind of a power-user feature that most users don't need to access directly.
Maybe for plotting when we have multiple backends again.

The same should work for plotting backends, but it's a little hard to test since we currently only have one. 

So, all that's left to do is to allow a list in config of backends to cycle though. Or is that even needed? We could just hardcode the list (I don't have if pycrates or pyfits are in the front) and pick that first one that works. The astro.io.backend is the main difference between the condif files for ciao-sherpa and standalone-sherpa. If we put this in, we would not have to distinguish between the two, they could use the same start-up file, and the conda recipes to build them could also be unified again.

**Comment by DougBurke** [comment]
More for background info rather than a response to @hamogu's comment above.

I think I've seen some "fun" issues when switching backends but I can't guarantee I'm remembering this right: I think the already-created plot objects were retaining a reference to the old plot backend, but this was in the context of some tests I was adding so I was probably doing something crazy (although for the plot code there is a relationship between object initialization and the backend).
