### ISSUE TITLE
How to link the boundary of one parameter to an others parameter's value

### ISSUE THREAD

**Issue by heidtgg** [sherpa/sherpa#362]
Hi,
I try to fit a spectrum with two model parameters. I can add the parameters with the command add_user_pars(...). I want to link the allowed minimal or maximal values to the value of the other parameter. Is this some how possible? I am working with a up-to-date installation of sherpa in python

Thanks In advance for the help
Thomas

**Comment by DougBurke** [comment]
Thomas,

I'm not 100% convinced I'm answering your question here, so please ask for clarification if I'm not. Sherpa allows you to link parameter values (e.g. to say that the foo parameter of model m1 should be 5 + the bar parameter of model m2) but I don't think this currently extends to parameter limits. That is, I don't think you can say that the foo parameter of model m1 should always be larger than the bar parameter of model m2. I'm trying to think if there's a way to "hack" the system to allow this, but nothing springs to mind (I may not have had enough coffee). Sometimes you can rewrite the function so that it has different parameters which let you enforce this constraint directly, but that is obviously not always possible.

You mention using add_user_pars, so I assume you are writing your own function rather than using one of Sherpa's inbuilt models?

Doug

**Comment by dtnguyen2** [comment]
I'm in the process of fixing the issue raised here, but I have two questions:

1) Currently the syntax for the link command is :

```link( par, val )```

see http://cxc.harvard.edu/sherpa/ahelp/link.html for details.  The question is: would the following interface be acceptable:

```link( par, val, min=None, max=None)```

So old scripts should work as before etc... and one can link the limit(s) of the parameter as:

```link(src1.pos, src2.pos + 2, min=src2.pos - 5)```
or
```link(src1.pos, src2.pos + 2, max=src2.pos + 8)```
or
```link(src1.pos, src2.pos + 2, min=src2.pos - 5, max=src2.pos + 8)```

2) Just to be clear, when the user wants to 
"I want to link the allowed minimal or maximal values to the value of the other parameter"
This is what he means:
```
>>> from sherpa.astro.ui import *
>>> gauss1d.src1
>>> gauss1d.src2
>>> src2.pos.val = -1
>>> link(src1.pos, src2.pos + 2, min=src2.pos - 5, max=src2.pos + 8)
>>> src1.pos.min
-6.0
>>> src2.pos.min
-3.4028234663852886e+38
>>> src1.pos.max
7.0
>>> src2.pos.max
3.4028234663852886e+38
```
right?

**Comment by DougBurke** [comment]
We are closing this ticket for now as it is unclear what the behavior should be:

- support a general expression, which is not feasible given our current design (as the limits are assumed to be fixed for the whole fit)
- just make them equal to another parameter's limits, for which we are struggling to come up with a use case

If anyone has use cases for this feature please create a new ticket and link to this one).
