### ISSUE TITLE
Can we not mark numpy as needed for installation (e.g. with pip)?

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#382]
```
% pip install sherpa
Collecting sherpa
  Downloading sherpa-4.9.1.tar.gz (8.8MB)
    100% |████████████████████████████████| 8.8MB 115kB/s 
    Complete output from command python setup.py egg_info:
    You need to install NUMPY in order to build Sherpa
    Other dependencies will be automatically installed
    Please install NUMPY (e.g. pip install numpy) and try again.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 2 in /tmp/pip-build-3oGsWV/sherpa/
```

If I then `pip install numpy` I can install Sherpa. Is there any reason we can not mark numpy as something that should be installed if it doesn't exist? I'm assuming the current behavior is historical.

**Comment by olaurino** [comment]
The reason was that `pip install numpy` would kick off a source build of `numpy`, which is complex, so it could be long and easily fail because of missing dependencies. By asking users to install `numpy` they can choose their favorite method of installation and, if they can't install `numpy` for whatever reason, that would be unrelated to Sherpa.

I see now that default `pip install` action for `numpy` is to install a binary wheel, so the original reason does not stand (at least for the most common platforms) anymore.

This is easy enough to fix, I'll issue a PR shortly. Thanks for bringing this up.

**Comment by olaurino** [comment]
Actually, I'll have to take some of that back. The reason for checking for `numpy` early was above all that we use `numpy.distutils.core` for importing `setup` to begin with, which is required to build the fortran extensions.

I don't really know whether there is a way to import `setup` from `setuptools` and still be able to build the fortran extensions. So, it's not so trivial to remove the *trap* we put in there, it requires some research into the dark recesses of the `distutils` commands and their extension. Also, we should probably bootstrap the `setuptools` installation as well.

**Comment by olaurino** [comment]
This SO question seems to provide a couple of good alternatives (one of which is the one I had in place originally, though):
https://stackoverflow.com/questions/19919905/how-to-bootstrap-numpy-installation-in-setup-py

**Comment by DougBurke** [comment]
Thanks for looking at this. I am not sure it's worth doing anything complicated, unless people start asking for it (and unfortunately the scipy link has bit-rotted in that it's not pointing to the relevant part anymore).

**Comment by olaurino** [comment]
It's not particularly urgent, but I'd prefer if we ironed those details out sooner or later.

**Comment by DougBurke** [comment]
We no longer have fortran extensions so maybe the comment in https://github.com/sherpa/sherpa/issues/382#issuecomment-320020291 is no-linger relevant?
