### ISSUE TITLE
XSsirf model reads outside of array

### ISSUE THREAD

**Issue by olaurino** [sherpa/sherpa#415]
While cleaning up and documenting #395 I came across this comment in `test_xspec` that was added in commit 864fa75:

> The sirf model - in 12.8.2 and up to 12.9.0d at least - includes
a read outside of an array. This has been seen to cause occasional
errors in the Sherpa test case, so it is removed from the test
for now. This problem has been reported to the XSPEC developers,
so it will hopefully be fixed in one of ther 12.9.0 patches.

I am creating this issue so we can check, sooner or later, whether this issue was fixed upstream or not. Not sure we documented a way to reproduce the issue or to test if was fixed.

**Comment by DougBurke** [comment]
I am pretty sure that I found this with the setup I've shown you before - create a small C program that creates a grid and evaluates the xssirf model on it with its default parameter set, and run it under valgrind.

**Comment by DougBurke** [comment]
It looks like it's fixed in XSPEC 12.9.1p - see https://gist.github.com/DougBurke/e2cbcea16d4c54f0c3374d0d48eb048e - for the code I checked. To be sure this should be built against 12.9.0d (say) to ensure that the code picks up a problem there (I would expect it to, but can't guarantee that this is exactly the same code as was originally used to claim there was an out-of-bounds read).
