### ISSUE TITLE
Add an easy way to remove a jdpileup model

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#441]
From a CIAO helpdesk enquiry:

`sherpa.astro.ui.set_pileup_model` is used to add a pileup kernel to a model for a PHA dataset. At present there doesn't appear to be an easy way to remove the pileup kernel. A suggested work around is to copy the data and source model expression to a new "dataset", which doesn't have a pileup kernel - e.g. (untested)

    set_data(2, get_data())
    set_source(2, get_source())

I think we could have it so that calling `set_pileup_model` with `model=None` would remove the pileup kernel; at present it fails with 

```
sherpa-11> set_pileup_model(id=1, model=None)
ArgumentTypeErr: 'model' must be a model object or model expression string
```

which comes from some internal code: `sherpa.ui.utils._set_item`.

**Comment by hamogu** [comment]
:+1: I;ve run into this as a user, too, and found it annoying.

**Comment by anetasie** [comment]
I have run into this problem too. There should be an easy way to remove the pileup model.
@DougBurke suggestion should be easy to implement.

**Comment by hamogu** [comment]
It's indeed easy to code, but there is an UI inconsistency here. Because `set_pileup_model` is in the ui layer, you can pass an id or not. In the function definition we have `def set_pileup_model(self, id, model=None)`. Thus `model=None` signals to the function, that the model is really set in the first variable (called "id") and to be used with the default id.

We would have to switch to a system where instead we try if the `id` is a valid id or, if not, if it should be treated as a model instance. Look for example at `set_pileup_model(my_var, model=None)`. Should that set the pileup model of the default id to `my_var` or should it remove the pileup model from dataset `my_var`? You don't know, unless you know if `my_var` is a number, a string, or a model instance. 

Once you know, you can decide, but I see some corner cases with not very helpful error messages.

What can be do?

- Go with @DougBurke suggestion. Despite what I said, I think that's the best, but I want us to agree before I make it a PR.
- Have a new function "remove_pileup_model"
- Choose some other special value (but which one?) for unsetting.

@anetasie : Do you have a preference?

**Comment by hamogu** [comment]
Another reason why the decision to have the id as first argument but have it optional at the some time if NOTAGOODIDEA (TM). 

Can we deprecate the ui layer, please? ;-)
