### ISSUE TITLE
Should we move to use packaging rather than distutils for version comparison

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#459]
Our current code base uses `LooseVersion` from distutils for version comparison. I saw a note in a random s̶p̶h̶i̶n̶x̶ code base that claims that `LooseVersion` is deprecated, and they were using `packaging.version.parse` to handle PEP-440 complaint version checks - e.g. https://packaging.pypa.io/en/latest/version/

Should we move towards this? I couldn't easily see documentation labelling `LooseVersion` as being deprecated but it wouldn't surprise me.

**Comment by olaurino** [comment]
Unfortunately the xspec version strings are not PEP-440 compliant, which is why we need to use `LooseVersion` in the first place:

```
In [1]: from distutils.version import LooseVersion
In [2]: LooseVersion("12.9.0i") > LooseVersion("12.9.0")
Out[2]: True

In [6]: from packaging.version import parse
In [7]: parse("12.9.0i") > parse("12.9.0")
Out[7]: False
```

The problem is that with `packaging.version.parse` non-PEP440 version strings always precede PEP440 version strings, while `LooseVersion` correctly implements comparisons among non-PEP440 versions.
