### ISSUE TITLE
Repeated test code related to ARF/RMF creation

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#518]
It looks like #482 ended up repeating some tests - e.g. `test_rspmodelnopha_delta_call` is in both `sherpa/astro/tests/test_astro_diag_arfrmf.py` and `sherpa/astro/tests/test_instrument.py`. I haven't checked closely, so there may be differences, but I note that they both fail the same way in https://travis-ci.org/sherpa/sherpa/jobs/440614460#L4148 which suggests that they are the same.

I think we should also update `sherpa/astro/tests/test_instrument.py` so that it uses the "top-level" create-an-arf / rmf functions added in #482 rather than having its own version (which predates #482), to reduce code duplication (and maybe improve test coverage).

**Comment by olaurino** [comment]
It looks like there are a bunch (at least two) of tests which are duplicated in the same way. Not sure what to do.

**Comment by olaurino** [comment]
It looks like the whole `test_astro_diag_arfrmf` was duplicating the tests in `test_instrument`, so I just moved the only additional test in the former to the latter, and removed the former. While it's not related to #503 I am going to push a commit there to fix this now, rather than punting it. Unless anybody has objections.

**Comment by olaurino** [comment]
Oh, and obviously I did as @DougBurke suggested, i.e. I removed the local implementation of the create functions in `test_instrument` so it's using the actual Sherpa implementations instead.
