### ISSUE TITLE
matplotlib 3 makes macos travis jobs fail

### ISSUE THREAD

**Issue by olaurino** [sherpa/sherpa#592]
See this job:
https://travis-ci.org/olaurino/sherpa/builds/489244858

**Comment by anetasie** [comment]
Is this only with new matplotlib? do you understand why?

**Comment by DougBurke** [comment]
Unfortunately the travis logs aren't very helpful. From what the test code runs, it's not clear to me that it is actually making any "serious" matplotlib calls - the tests mainly check we can set up the necessary objects without creating the actual plots - so I wonder if the fact there's a crash here is a "red herring", and the problem is elsewhere. However, this is all just guesswork on my part as I haven't tried to replicate the problem, and I really should just let @olaurino answer ;-)

**Comment by olaurino** [comment]
I didn't look into it yet. I believe this is related to the issue I reported on Dec 8 to sherpadev, which doesn't have anything to do with Sherpa, only the combination of matplotlib version + python version on macOS.

**Comment by DougBurke** [comment]
Should we try the work-around you mentioned in your initial investigation (note that we now see this with matplotlib 3.0.2 whereas the original analysis was with matplotlib 3.0.1) - that is force a particular matplotlib backend for the relevant test files. So something like

```
# since it's not easy to find out the chosen sherpa plot backend without loading matpotlib
try:
    import matplotlib
    matplotlib.use('Agg')
except ImportError:
  pass  # assume using chips or no plot backend
```

**Comment by hamogu** [comment]
I just tried to install matplotlib 3.0.2 from anaconda on my Mac Laptop and it crashed every time on import. I can see, but not understand, error messages and some quick googeleing indicates that matplotlib and python are complied with different compiler versions or something like that. For my laptop, I'm convinced that the error is with the conda builds. Since you only see this on macos, it might well be the same issue - just a conda build problem and not a real issue in the code.

**Comment by DougBurke** [comment]
We now run the macOS travis job with matplotlib 3 (as part of pr #626) so whatever caused this has been fixed.
