### ISSUE TITLE
Move testing to tox

### ISSUE THREAD

**Issue by DougBurke** [sherpa/sherpa#715]
We currently use `python setup.py test` to run our test suite, but its time is running out, since with a recent `pytest` we can see this warning message

```
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
```

(or look around on the web for articles about this). So we should look at moving to `tox` (I've not been following closely enough to know if there's other options, but I think we should just use `tox`).

**Comment by olaurino** [comment]
The problem with tox was that it didn't work with conda's virtualenv. Other than that using tox is a no-brainer especially because it abstracts from the testing environment.

I recently looked into tox/conda for a recent project where I needed some dependencies to be installed through conda but still wanted to use tox. There is a tox-conda plugin, it kind of works, but it doesn't feel like there is a ton of support: https://github.com/tox-dev/tox-conda

For my side project it was good enough.

**Comment by hamogu** [comment]
For what it's worth: Astropy has just decided to move to tox, too https://github.com/astropy/astropy-APEs/blob/master/APE17.rst
I have not followed the discussion closely, but people in the astropy team have experimented with tox and conda and still decided that that's the way forward.

**Comment by hamogu** [comment]
I just moved saba to tox astropy/saba#35 and find that it works well. Locally I use tox-conda and on travis I don't.

**Comment by DougBurke** [comment]
I'm closing this issue as we haven't decided to go with `tox` (not that we haven't decided not too, but we haven't seen a pressing need).
