### ISSUE TITLE
Test examples in the docs

### ISSUE THREAD

**Issue by hamogu** [sherpa/sherpa#816]
The CI should include a run that tests the examples in the docs (pytest extension 'doctest-plus' work well for that). That should catch cases like https://github.com/sherpa/sherpa/pull/815 and makes sure that the examples are up-to-date with any code / parameter names changes.

**Comment by hamogu** [comment]
xref #784

**Comment by DougBurke** [comment]
I haven't done this in the past

a) for lack of time

b) there is *an* argument to be made about being careful to ensure that document updates are intentional (that is, to make sure some change hasn't happened "by accident"). I don't think this argument is should stop improvements to the automation of the documentation, but it's something I think about as there have been (and probably still are) cases where code and documentation disagree, and then how do we work out which is correct?

**Comment by hamogu** [comment]
Of course for cases where docs and code diverge, we need to make a decision, what the "right" things to do should be.

But it needs to be done - because we want users to be able to use the docs to understand how to use sherpa. We don't want them to accidentally diverge (because then users need to read the code to find how the options are called) and the only way to stop that is to run the doc examples. 

I promise that in 90% of the cases failures are either typos or intentional changes not applied to the docs.

BTW: Nice to have you back!

**Comment by DougBurke** [comment]
I have to admit that my earlier comment was due to me reading this wrongly - it was more aimed at a discussion Omar and myself have had about generating the documentation output at build time rather than this issue.

**Comment by hamogu** [comment]
This is not complete, but all the infrastructure is in place and we test more an more of the examples in the docs. I feel this does not need an extra issue any more; we just address this as we work on docs. Thus, I'm closing this issue.
An alternative would be to turn this issue into a list to be ticked of module my module, but that's just duplicating the exclusion list for doctestplus in the configuration files.
